In [2]:
import pandas as pd

In [5]:
df_sf = pd.read_csv("/home/tim/Schreibtisch/2024-25-Data_Librarian-Reschop_Tim/Modul_3/Data/Library_Usage.csv", low_memory=False)
df_sf

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
0,Senior,5,0,75 years and over,Main,Nov,2022,Email,True,2015,False
1,Adult,0,0,45 to 54 years,Main,Jul,2023,Email,True,2019,False
2,Adult,0,0,55 to 59 years,Western Addition,Mar,2024,Email,True,2022,False
3,Welcome,1,1,20 to 24 years,Richmond,Aug,2022,Email,True,2022,False
4,Senior,0,0,65 to 74 years,Sunset,Mar,2024,Print,False,2023,False
...,...,...,...,...,...,...,...,...,...,...,...
450354,Digital Access Card,0,0,35 to 44 years,Ingleside,Null,Null,Email,False,2023,Null
450355,Digital Access Card,0,0,45 to 54 years,Ingleside,Aug,2022,Print,False,2022,Null
450356,Digital Access Card,0,0,25 to 34 years,Ingleside,Aug,2022,Print,False,2022,Null
450357,Digital Access Card,0,0,35 to 44 years,Ingleside,Apr,2022,Print,False,2022,Null
450358,Digital Access Card,0,0,65 to 74 years,Bayview,Apr,2023,Email,False,2023,Null

In [4]:
df_sf.memory_usage()

Index                               132
Patron Type Definition          3602872
Total Checkouts                 3602872
Total Renewals                  3602872
Age Range                       3602872
Home Library Definition         3602872
Circulation Active Month        3602872
Circulation Active Year         3602872
Notice Preference Definition    3602872
Provided Email Address           450359
Year Patron Registered          3602872
Within San Francisco County     3602872
dtype: int64

In [26]:
df_sf['Circulation Active Year'] = pd.to_numeric(
    df_sf['Circulation Active Year'], errors='coerce'
)

df_sf['Year Patron Registered'] = pd.to_numeric(
    df_sf['Circulation Active Year'], errors='coerce'
)

In [27]:
df_sf['Circulation Active Month'] = pd.to_datetime(
                                        df_sf['Circulation Active Month'],
                                        errors='coerce',
                                        format="%b"
                                    )

In [28]:
df_sf['Circulation Active Month'].dt.month

0         11.0
1          7.0
2          3.0
3          8.0
4          3.0
          ...
450354     NaN
450355     8.0
450356     8.0
450357     4.0
450358     4.0
Name: Circulation Active Month, Length: 450359, dtype: float64

In [32]:
df_sf['Membership Duration'] = (df_sf['Circulation Active Year'] - df_sf['Year Patron Registered'])*12 + df_sf['Circulation Active Month'].dt.month
df_sf

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
0,Senior,5,0,75 years and over,Main,1900-11-01,2022.0,Email,True,2022.0,False,11.0
1,Adult,0,0,45 to 54 years,Main,1900-07-01,2023.0,Email,True,2023.0,False,7.0
2,Adult,0,0,55 to 59 years,Western Addition,1900-03-01,2024.0,Email,True,2024.0,False,3.0
3,Welcome,1,1,20 to 24 years,Richmond,1900-08-01,2022.0,Email,True,2022.0,False,8.0
4,Senior,0,0,65 to 74 years,Sunset,1900-03-01,2024.0,Print,False,2024.0,False,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
450354,Digital Access Card,0,0,35 to 44 years,Ingleside,NaT,NaN,Email,False,NaN,Null,NaN
450355,Digital Access Card,0,0,45 to 54 years,Ingleside,1900-08-01,2022.0,Print,False,2022.0,Null,8.0
450356,Digital Access Card,0,0,25 to 34 years,Ingleside,1900-08-01,2022.0,Print,False,2022.0,Null,8.0
450357,Digital Access Card,0,0,35 to 44 years,Ingleside,1900-04-01,2022.0,Print,False,2022.0,Null,4.0
450358,Digital Access Card,0,0,65 to 74 years,Bayview,1900-04-01,2023.0,Email,False,2023.0,Null,4.0

In [34]:
df_sf['Membership Duration'] = df_sf['Membership Duration'].fillna(0)
df_sf

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
0,Senior,5,0,75 years and over,Main,1900-11-01,2022.0,Email,True,2022.0,False,11.0
1,Adult,0,0,45 to 54 years,Main,1900-07-01,2023.0,Email,True,2023.0,False,7.0
2,Adult,0,0,55 to 59 years,Western Addition,1900-03-01,2024.0,Email,True,2024.0,False,3.0
3,Welcome,1,1,20 to 24 years,Richmond,1900-08-01,2022.0,Email,True,2022.0,False,8.0
4,Senior,0,0,65 to 74 years,Sunset,1900-03-01,2024.0,Print,False,2024.0,False,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
450354,Digital Access Card,0,0,35 to 44 years,Ingleside,NaT,NaN,Email,False,NaN,Null,0.0
450355,Digital Access Card,0,0,45 to 54 years,Ingleside,1900-08-01,2022.0,Print,False,2022.0,Null,8.0
450356,Digital Access Card,0,0,25 to 34 years,Ingleside,1900-08-01,2022.0,Print,False,2022.0,Null,8.0
450357,Digital Access Card,0,0,35 to 44 years,Ingleside,1900-04-01,2022.0,Print,False,2022.0,Null,4.0
450358,Digital Access Card,0,0,65 to 74 years,Bayview,1900-04-01,2023.0,Email,False,2023.0,Null,4.0

In [37]:
df_sf['Total Checkouts'] > 10000

0         False
1         False
2         False
3         False
4         False
          ...
450354    False
450355    False
450356    False
450357    False
450358    False
Name: Total Checkouts, Length: 450359, dtype: bool

In [38]:
row_filter = (df_sf['Patron Type Definition'] == 'Senior') & (df_sf['Notice Preference Definition'] == 'Email')
df_sf.loc[row_filter]

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
0,Senior,5,0,75 years and over,Main,1900-11-01,2022.0,Email,True,2022.0,False,11.0
5,Senior,0,0,75 years and over,Main,1900-04-01,2021.0,Email,True,2021.0,False,4.0
27,Senior,0,0,75 years and over,Main,1900-10-01,2023.0,Email,True,2023.0,False,10.0
28,Senior,0,0,65 to 74 years,Main,1900-03-01,2024.0,Email,True,2024.0,False,3.0
29,Senior,0,0,65 to 74 years,Main,1900-08-01,2023.0,Email,True,2023.0,False,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...
450101,Senior,0,0,75 years and over,Main,1900-03-01,2024.0,Email,True,2024.0,False,3.0
450102,Senior,0,0,65 to 74 years,Noe Valley,1900-03-01,2024.0,Email,True,2024.0,False,3.0
450142,Senior,0,0,65 to 74 years,Main,1900-11-01,2022.0,Email,True,2022.0,Null,11.0
450143,Senior,0,0,65 to 74 years,Main,1900-03-01,2024.0,Email,True,2024.0,Null,3.0
450144,Senior,1,0,75 years and over,Main,1900-01-01,2024.0,Email,True,2024.0,Null,1.0

In [42]:
row_filter2 = (df_sf['Age Range'] == '0 to 9 years')
df_sf.loc[row_filter2]

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
14,Teacher Card,0,0,0 to 9 years,Main,NaT,NaN,Email,True,NaN,False,0.0
1067,Adult,0,0,0 to 9 years,Richmond,1900-12-01,2022.0,Phone,False,2022.0,False,12.0
1487,Juvenile,0,0,0 to 9 years,Main,NaT,NaN,Email,True,NaN,False,0.0
1488,Juvenile,0,0,0 to 9 years,Main,NaT,NaN,Email,True,NaN,False,0.0
1491,Juvenile,0,0,0 to 9 years,Main,1900-06-01,2023.0,Email,True,2023.0,False,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...
450241,Juvenile,0,0,0 to 9 years,Bernal Heights,NaT,NaN,Email,True,NaN,Null,0.0
450244,Juvenile,2,2,0 to 9 years,Bayview,1900-10-01,2023.0,Email,False,2023.0,Null,10.0
450245,Juvenile,0,0,0 to 9 years,Bayview,NaT,NaN,Email,False,NaN,Null,0.0
450246,Juvenile,2,2,0 to 9 years,Bayview,1900-10-01,2023.0,Email,False,2023.0,Null,10.0
450247,Juvenile,11,15,0 to 9 years,Bayview,1900-03-01,2022.0,Email,True,2022.0,Null,3.0

In [ ]:
#33180 Personen sind unter 10 Jahren

In [48]:
df_sf['Total Checkouts'].unique

<bound method Series.unique of 0         5
1         0
2         0
3         1
4         0
         ..
450354    0
450355    0
450356    0
450357    0
450358    0
Name: Total Checkouts, Length: 450359, dtype: int64>

In [51]:
df_sf['Total Checkouts'] = pd.to_numeric(
    df_sf['Total Checkouts'], errors='coerce'
)

row_filter3 = (df_sf['Total Checkouts'] >= 20000)
df_sf.loc[row_filter3]

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
60282,Senior,20561,1021,65 to 74 years,Main,1900-03-01,2024.0,Phone,False,2024.0,True,3.0
60622,Senior,23134,617,65 to 74 years,Main,1900-03-01,2024.0,Print,False,2024.0,True,3.0
60994,Senior,21890,16,75 years and over,Main,1900-01-01,2023.0,Email,True,2023.0,True,1.0
179460,Adult,35176,62,25 to 34 years,Sunset,1900-03-01,2024.0,Email,True,2024.0,True,3.0
234329,Adult,23345,6458,55 to 59 years,Chinatown,1900-03-01,2024.0,Email,True,2024.0,True,3.0
234381,Adult,24386,387,45 to 54 years,Chinatown,1900-03-01,2024.0,Phone,False,2024.0,True,3.0
293994,Adult,39743,659,60 to 64 years,Ortega,1900-03-01,2024.0,Email,True,2024.0,True,3.0

In [ ]:
#7 Personen haben mehr als 20000 Ausleihen

In [57]:
row_filter4 = (df_sf['Home Library Definition'] == "Richmond")
df_sf.loc[row_filter4]

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
3,Welcome,1,1,20 to 24 years,Richmond,1900-08-01,2022.0,Email,True,2022.0,False,8.0
228,Senior,0,0,65 to 74 years,Richmond,1900-02-01,2024.0,Email,True,2024.0,False,2.0
229,Senior,0,0,75 years and over,Richmond,1900-02-01,2024.0,Email,True,2024.0,False,2.0
230,Senior,7,19,65 to 74 years,Richmond,1900-03-01,2024.0,Email,True,2024.0,False,3.0
231,Senior,0,0,65 to 74 years,Richmond,1900-01-01,2024.0,Email,True,2024.0,False,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
450159,Adult,0,0,25 to 34 years,Richmond,NaT,NaN,Email,True,NaN,Null,0.0
450198,Juvenile,0,0,10 to 19 years,Richmond,1900-07-01,2023.0,Email,False,2023.0,Null,7.0
450255,Teen,1,0,20 to 24 years,Richmond,1900-02-01,2024.0,Email,False,2024.0,Null,2.0
450256,Teen,1288,109,10 to 19 years,Richmond,1900-08-01,2023.0,Email,True,2023.0,Null,8.0
450291,Digital Access Card,0,0,35 to 44 years,Richmond,1900-04-01,2023.0,Email,False,2023.0,Null,4.0

In [ ]:
#21433 kommen aus Richmond

In [58]:
row_filter5 = (df_sf['Membership Duration'] == 0)
df_sf.loc[row_filter5]

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
14,Teacher Card,0,0,0 to 9 years,Main,NaT,NaN,Email,True,NaN,False,0.0
17,Teacher Card,0,0,45 to 54 years,Main,NaT,NaN,Email,True,NaN,False,0.0
36,Senior,0,0,65 to 74 years,Main,NaT,NaN,Email,True,NaN,False,0.0
93,Senior,0,0,65 to 74 years,Main,NaT,NaN,Email,True,NaN,False,0.0
127,Senior,0,0,65 to 74 years,Main,NaT,NaN,Email,True,NaN,False,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
450321,Digital Access Card,0,0,60 to 64 years,Glen Park,NaT,NaN,Email,False,NaN,Null,0.0
450324,Digital Access Card,0,0,45 to 54 years,Glen Park,NaT,NaN,Email,False,NaN,Null,0.0
450339,Digital Access Card,0,0,75 years and over,Marina,NaT,NaN,Email,True,NaN,Null,0.0
450340,Digital Access Card,0,0,45 to 54 years,Marina,NaT,NaN,Email,True,NaN,Null,0.0
450354,Digital Access Card,0,0,35 to 44 years,Ingleside,NaT,NaN,Email,False,NaN,Null,0.0

In [59]:
#ungefähr 10% haben eine Duration von 0

In [60]:
df_sf.isna().sum()

Patron Type Definition              0
Total Checkouts                     0
Total Renewals                      0
Age Range                           0
Home Library Definition             0
Circulation Active Month        40317
Circulation Active Year         40317
Notice Preference Definition        0
Provided Email Address              0
Year Patron Registered          40317
Within San Francisco County         0
Membership Duration                 0
dtype: int64

In [63]:
df_sf_clean = df_sf.dropna()
df_sf_clean

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
0,Senior,5,0,75 years and over,Main,1900-11-01,2022.0,Email,True,2022.0,False,11.0
1,Adult,0,0,45 to 54 years,Main,1900-07-01,2023.0,Email,True,2023.0,False,7.0
2,Adult,0,0,55 to 59 years,Western Addition,1900-03-01,2024.0,Email,True,2024.0,False,3.0
3,Welcome,1,1,20 to 24 years,Richmond,1900-08-01,2022.0,Email,True,2022.0,False,8.0
4,Senior,0,0,65 to 74 years,Sunset,1900-03-01,2024.0,Print,False,2024.0,False,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
450353,Digital Access Card,0,0,35 to 44 years,Ingleside,1900-01-01,2023.0,Email,False,2023.0,Null,1.0
450355,Digital Access Card,0,0,45 to 54 years,Ingleside,1900-08-01,2022.0,Print,False,2022.0,Null,8.0
450356,Digital Access Card,0,0,25 to 34 years,Ingleside,1900-08-01,2022.0,Print,False,2022.0,Null,8.0
450357,Digital Access Card,0,0,35 to 44 years,Ingleside,1900-04-01,2022.0,Print,False,2022.0,Null,4.0
450358,Digital Access Card,0,0,65 to 74 years,Bayview,1900-04-01,2023.0,Email,False,2023.0,Null,4.0

In [64]:
df_sf.to_csv("/home/tim/Schreibtisch/2024-25-Data_Librarian-Reschop_Tim/Modul_3/Data/Library_Usage_Clean.csv")

In [65]:
df_sf.head(100)

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
0,Senior,5,0,75 years and over,Main,1900-11-01,2022.0,Email,True,2022.0,False,11.0
1,Adult,0,0,45 to 54 years,Main,1900-07-01,2023.0,Email,True,2023.0,False,7.0
2,Adult,0,0,55 to 59 years,Western Addition,1900-03-01,2024.0,Email,True,2024.0,False,3.0
3,Welcome,1,1,20 to 24 years,Richmond,1900-08-01,2022.0,Email,True,2022.0,False,8.0
4,Senior,0,0,65 to 74 years,Sunset,1900-03-01,2024.0,Print,False,2024.0,False,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,Senior,81,37,75 years and over,Main,1900-06-01,2023.0,Email,True,2023.0,False,6.0
96,Senior,0,0,65 to 74 years,Main,1900-10-01,2023.0,Null,False,2023.0,False,10.0
97,Senior,0,0,65 to 74 years,Main,1900-03-01,2024.0,Email,True,2024.0,False,3.0
98,Senior,0,0,65 to 74 years,Main,1900-03-01,2024.0,Email,True,2024.0,False,3.0
99,Senior,1,0,75 years and over,Main,1900-03-01,2020.0,Email,True,2020.0,False,3.0

In [67]:
len(df_sf)

450359

In [68]:
row_filter6 = (df_sf['Age Range'] == "60 to 64 years") & (df_sf['Circulation Active Year'] == 2016)
df_sf.loc[row_filter6]

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
2569,Adult,2,0,60 to 64 years,Main,1900-06-01,2016.0,Email,True,2016.0,False,6.0
6582,Adult,11,24,60 to 64 years,Main,1900-05-01,2016.0,Email,True,2016.0,False,5.0
30085,Adult,3,0,60 to 64 years,Main,1900-03-01,2016.0,Email,True,2016.0,False,3.0
45433,Adult,21,5,60 to 64 years,Main,1900-04-01,2016.0,Email,True,2016.0,False,4.0
108311,Adult,56,2,60 to 64 years,Main,1900-07-01,2016.0,Print,True,2016.0,True,7.0
116078,Adult,96,2,60 to 64 years,Main,1900-08-01,2016.0,Email,True,2016.0,True,8.0
117973,Adult,13,0,60 to 64 years,Main,1900-02-01,2016.0,Email,True,2016.0,True,2.0
211971,Adult,3,3,60 to 64 years,Merced,1900-05-01,2016.0,Email,True,2016.0,True,5.0
232885,Adult,51,4,60 to 64 years,Chinatown,1900-08-01,2016.0,Email,True,2016.0,True,8.0
233915,Adult,80,4,60 to 64 years,Chinatown,1900-10-01,2016.0,Email,True,2016.0,True,10.0
244151,Adult,4,0,60 to 64 years,Mission,1900-07-01,2016.0,Email,True,2016.0,True,7.0
285449,Adult,2408,2331,60 to 64 years,Marina,1900-06-01,2016.0,Email,True,2016.0,True,6.0
328217,Adult,1,2,60 to 64 years,Bayview,1900-12-01,2016.0,Email,True,2016.0,True,12.0
328412,Adult,12,7,60 to 64 years,Bayview,1900-12-01,2016.0,Email,True,2016.0,True,12.0
441231,Adult,1,0,60 to 64 years,Main,1900-04-01,2016.0,Email,True,2016.0,False,4.0
442082,Adult,15,3,60 to 64 years,Park,1900-08-01,2016.0,Email,True,2016.0,False,8.0

In [70]:
len(df_sf.loc[row_filter6])

16

In [72]:
df_sf = df_sf.dropna()
df_sf

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County,Membership Duration
0,Senior,5,0,75 years and over,Main,1900-11-01,2022.0,Email,True,2022.0,False,11.0
1,Adult,0,0,45 to 54 years,Main,1900-07-01,2023.0,Email,True,2023.0,False,7.0
2,Adult,0,0,55 to 59 years,Western Addition,1900-03-01,2024.0,Email,True,2024.0,False,3.0
3,Welcome,1,1,20 to 24 years,Richmond,1900-08-01,2022.0,Email,True,2022.0,False,8.0
4,Senior,0,0,65 to 74 years,Sunset,1900-03-01,2024.0,Print,False,2024.0,False,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
450353,Digital Access Card,0,0,35 to 44 years,Ingleside,1900-01-01,2023.0,Email,False,2023.0,Null,1.0
450355,Digital Access Card,0,0,45 to 54 years,Ingleside,1900-08-01,2022.0,Print,False,2022.0,Null,8.0
450356,Digital Access Card,0,0,25 to 34 years,Ingleside,1900-08-01,2022.0,Print,False,2022.0,Null,8.0
450357,Digital Access Card,0,0,35 to 44 years,Ingleside,1900-04-01,2022.0,Print,False,2022.0,Null,4.0
450358,Digital Access Card,0,0,65 to 74 years,Bayview,1900-04-01,2023.0,Email,False,2023.0,Null,4.0