In [2]:
import pyterrier as pt
import requests
import pandas as pd
import pickle
import nltk
import numpy as np
%pip install xlrd

Requirement already satisfied: xlrd in /home/tim/anaconda3/lib/python3.12/site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [3]:
df_alma = pd.read_excel('alma_beck.xlsx', sheet_name='getFullTxt')

In [4]:
df_alma

,LOCALIZED,ISSN,ISSN.1,ISSN.2,ISBN1,ISBN2,ISBN3,OTHER_SYSTEM_NUMBER1,OTHER_SYSTEM_NUMBER2,OTHER_SYSTEM_NUMBER3,...,LICENSE,LICENSE_NAME,COLLECTION_LICENSE,COLLECTION_LICENSE_NAME,PDA,EBA,PO_LINE,LANGUAGE,COUNTER_PLATFORM,NOTES
0,N,NaN,NaN,NaN,9783406751332,9.783407e+12,NaN,(ALEPH)020383966EDU01,(DE-465)LT001916108,LT001916108,...,NaN,NaN,NaN,NaN,NaN,NaN,UB23-25962,ger,NaN,NaN
1,N,NaN,NaN,NaN,9783406749360,9.783407e+12,NaN,(ALEPH)020383935EDU01,(DE-465)LT001916077,LT001916077,...,NaN,NaN,NaN,NaN,NaN,NaN,UB23-25962,ger,NaN,NaN
2,N,NaN,NaN,NaN,9783406747298,9.783407e+12,NaN,(ALEPH)020383920EDU01,(DE-465)LT001916062,LT001916062,...,NaN,NaN,NaN,NaN,NaN,NaN,UB23-25962,ger,NaN,NaN
3,N,NaN,NaN,NaN,9783406757808,9.783407e+12,NaN,(ALEPH)020384028EDU01,(DE-465)LT001916170,LT001916170,...,NaN,NaN,NaN,NaN,NaN,NaN,UB23-25962,ger,NaN,NaN
4,N,NaN,NaN,NaN,9783406745843,9.783407e+12,NaN,(ALEPH)020383917EDU01,(DE-465)LT001916059,LT001916059,...,NaN,NaN,NaN,NaN,NaN,NaN,UB23-25962,ger,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4826,N,NaN,NaN,NaN,9783406822100,9.783407e+12,NaN,(Verlag,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,UB23-25962,ger,NaN,NaN
4827,N,NaN,NaN,NaN,9783406823749,9.783407e+12,NaN,(Verlag,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,UB23-25962,ger,NaN,NaN
4828,N,NaN,NaN,NaN,9783406817359,9.783407e+12,NaN,(Verlag,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,UB23-25962,ger,NaN,NaN
4829,N,NaN,NaN,NaN,9783406822445,9.783407e+12,NaN,(Verlag,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,UB23-25962,ger,NaN,NaN
4830,N,NaN,NaN,NaN,9783406792441,9.783407e+12,NaN,(Verlag,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,UB23-25962,ger,NaN,NaN

In [5]:
df_alma.columns

Index(['LOCALIZED', 'ISSN', 'ISSN.1', 'ISSN.2', 'ISBN1', 'ISBN2', 'ISBN3',
       'OTHER_SYSTEM_NUMBER1', 'OTHER_SYSTEM_NUMBER2', 'OTHER_SYSTEM_NUMBER3',
       'PORTFOLIO_PID', 'MMS', 'TITLE', 'FROM_YEAR', 'TO_YEAR', 'FROM_MONTH',
       'TO_MONTH', 'FROM_DAY', 'TO_DAY', 'FROM_VOLUME', 'TO_VOLUME',
       'FROM_ISSUE', 'TO_ISSUE', 'PUBLICATION_DATE_OPERATOR',
       'PUBLICATION_DATE_YEAR', 'PUBLICATION_DATE_MONTH', 'GLOBAL_FROM_YEAR',
       'GLOBAL_TO_YEAR', 'GLOBAL_FROM_MONTH', 'GLOBAL_TO_MONTH',
       'GLOBAL_FROM_DAY', 'GLOBAL_TO_DAY', 'GLOBAL_FROM_VOLUME',
       'GLOBAL_TO_VOLUME', 'GLOBAL_FROM_ISSUE', 'GLOBAL_TO_ISSUE',
       'GLOBAL_PUBLICATION_DATE_OPERATOR', 'GLOBAL_PUBLICATION_DATE_YEAR',
       'GLOBAL_PUBLICATION_DATE_MONTH', 'ACCESS_TYPE', 'PERPETUAL_FROM_YEAR',
       'PERPETUAL_TO_YEAR', 'PERPETUAL_FROM_MONTH', 'PERPETUAL_TO_MONTH',
       'PERPETUAL_FROM_DAY', 'PERPETUAL_TO_DAY', 'PERPETUAL_FROM_VOLUME',
       'PERPETUAL_TO_VOLUME', 'PERPETUAL_FROM_ISSUE', 'PERPETUAL_TO_ISSUE',
       'PERPETUAL_PUBLICATION_DATE_OPERATOR',
       'PERPETUAL_PUBLICATION_DATE_YEAR', 'PERPETUAL_PUBLICATION_DATE_MONTH',
       'AVAILABILITY', 'PUBLISHER', 'PLACE_OF_PUBLICATION',
       'DATE_OF_PUBLICATION', 'URL', 'PARSER_PARAMETERS', 'PROXY_ENABLE',
       'PROXY_SELECTED', 'PROXY_LEVEL', 'AUTHOR', 'ELECTRONIC_MATERIAL_TYPE',
       'OWNERSHIP', 'GROUP_NAME', 'GROUP_FROM_YEAR', 'GROUP_TO_YEAR',
       'GROUP_FROM_MONTH', 'GROUP_TO_MONTH', 'GROUP_FROM_DAY', 'GROUP_TO_DAY',
       'GROUP_FROM_VOLUME', 'GROUP_TO_VOLUME', 'GROUP_FROM_ISSUE',
       'GROUP_TO_ISSUE', 'GROUP_PUBLICATION_DATE_OPERATOR',
       'GROUP_PUBLICATION_DATE_YEAR', 'GROUP_PUBLICATION_DATE_MONTH',
       'GROUP_PROXY_ENABLE', 'GROUP_PROXY_SELECTED',
       'GROUP_AUTHENTICATION_NOTES', 'GROUP_PUBLIC_NOTES',
       'AUTHENTICATION_NOTES', 'PUBLIC_NOTES', 'INTERNAL_DESCRIPTION',
       'COVERAGE_STATEMENT', 'ACTIVATION_DATE', 'EXPECTED_ACTIVATION_DATE',
       'LICENSE', 'LICENSE_NAME', 'COLLECTION_LICENSE',
       'COLLECTION_LICENSE_NAME', 'PDA', 'EBA', 'PO_LINE', 'LANGUAGE',
       'COUNTER_PLATFORM', 'NOTES'],
      dtype='object')

In [8]:
df_alma_sorted = df_alma[['ISBN1', 'TITLE', 'AUTHOR', 'DATE_OF_PUBLICATION', 'URL', 'ELECTRONIC_MATERIAL_TYPE', 'LANGUAGE']]
df_alma_sorted

,ISBN1,TITLE,AUTHOR,DATE_OF_PUBLICATION,URL,ELECTRONIC_MATERIAL_TYPE,LANGUAGE
0,9783406751332,Sir William Siemens Elektronische Ressource 18...,"König, Wolfgang",2020,https://doi.org/10.17104/9783406751356,DOCUMENT,ger
1,9783406749360,Johannes Paul II. Elektronische Ressource Der ...,"Drobinski, Matthias",2020,https://doi.org/10.17104/9783406749384,DOCUMENT,ger
2,9783406747298,Das wichtigste Wissen Elektronische Ressource ...,"Fischer, Ernst Peter",2020,https://doi.org/10.17104/9783406747311,DOCUMENT,ger
3,9783406757808,Polizei- und Ordnungsrecht Elektronische Resso...,"Kingreen, Thorsten",2020,https://doi.org/10.17104/9783406759697,DOCUMENT,ger
4,9783406745843,Allgemeines Schuldrecht Elektronische Ressourc...,"Brox, Hans",2020,https://doi.org/10.17104/9783406747472,DOCUMENT,ger
...,...,...,...,...,...,...,...
4826,9783406822100,Sonderzug nach Moskau Geschichte der deutschen...,"Scianna, Bastian Matteo author",2024,https://doi.org/10.17104/9783406822117,BOOK,ger
4827,9783406823749,"Arbeitsrecht Wilhelm Dütz, Gregor Thüsing","Dütz, Wilhelm author",2024,https://doi.org/10.17104/9783406823756,BOOK,ger
4828,9783406817359,Unter deutscher Besatzung Europa 1939-1945 Tat...,"Tönsmeyer, Tatjana author",2024,https://doi.org/10.17104/9783406817373,BOOK,ger
4829,9783406822445,Geschichte der arabischen Welt Andreas Kaplony,NaN,2024,https://doi.org/10.17104/9783406822452,BOOK,ger
4830,9783406792441,Sachenrecht Wolfgang Lüke,"Lüke, Wolfgang author",2024,https://doi.org/10.17104/9783406792458,BOOK,ger

In [11]:
df_alma_doc = df_alma_sorted[df_alma_sorted['ELECTRONIC_MATERIAL_TYPE'] == "DOCUMENT"] 
df_alma_doc

,ISBN1,TITLE,AUTHOR,DATE_OF_PUBLICATION,URL,ELECTRONIC_MATERIAL_TYPE,LANGUAGE
0,9783406751332,Sir William Siemens Elektronische Ressource 18...,"König, Wolfgang",2020,https://doi.org/10.17104/9783406751356,DOCUMENT,ger
1,9783406749360,Johannes Paul II. Elektronische Ressource Der ...,"Drobinski, Matthias",2020,https://doi.org/10.17104/9783406749384,DOCUMENT,ger
2,9783406747298,Das wichtigste Wissen Elektronische Ressource ...,"Fischer, Ernst Peter",2020,https://doi.org/10.17104/9783406747311,DOCUMENT,ger
3,9783406757808,Polizei- und Ordnungsrecht Elektronische Resso...,"Kingreen, Thorsten",2020,https://doi.org/10.17104/9783406759697,DOCUMENT,ger
4,9783406745843,Allgemeines Schuldrecht Elektronische Ressourc...,"Brox, Hans",2020,https://doi.org/10.17104/9783406747472,DOCUMENT,ger
...,...,...,...,...,...,...,...
2998,9783791046099,Buchführung und Bilanzierung in der Sozialwirt...,"Schwien, Bernd",2020,https://doi.org/10.34156/9783791046112,DOCUMENT,ger
2999,9783800636143,Internationale betriebswirtschaftliche Steuerl...,"Scheffler, Wolfram",2009,https://doi.org/10.15358/9783800644063,DOCUMENT,ger
3000,9783800637911,The Innovator's Dilemma Elektronische Ressourc...,"Christensen, Clayton M.",2011,https://doi.org/10.15358/9783800642816,DOCUMENT,ger
3001,9783791042954,Wirtschaftsthemen verständlich vermitteln Elek...,"Hesse, Nils",2019,https://doi.org/10.34156/9783791042978,DOCUMENT,ger
3002,9783800634606,Produktionstheorie Elektronische Ressource Joa...,"Schwalbach, Joachim",2008,https://doi.org/10.15358/9783800643943,DOCUMENT,ger

In [12]:
if not pt.started():
    pt.init()

/tmp/ipykernel_3420/3057724015.py:1: DeprecationWarning: Call to deprecated function (or staticmethod) started. (use pt.java.started() instead) -- Deprecated since version 0.11.0.
  if not pt.started():
Java started and loaded: pyterrier.java, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]
/tmp/ipykernel_3420/3057724015.py:2: DeprecationWarning: Call to deprecated method pt.init(). Deprecated since version 0.11.0.
java is now started automatically with default settings. To force initialisation early, run:
pt.java.init() # optional, forces java initialisation
  pt.init()

In [14]:
#Umbenennung der Spalten zur Vorbereitung auf die Indexierung/Dokumentenrepräsentation
df_alma_doc['docno'] = df_alma_doc['ISBN1']
df_alma_doc['text'] = df_alma_doc['TITLE']
df_alma_doc

/tmp/ipykernel_3420/2028849501.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_alma_doc['docno'] = df_alma_doc['ISBN1']
/tmp/ipykernel_3420/2028849501.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_alma_doc['text'] = df_alma_doc['TITLE']

,ISBN1,TITLE,AUTHOR,DATE_OF_PUBLICATION,URL,ELECTRONIC_MATERIAL_TYPE,LANGUAGE,docno,text
0,9783406751332,Sir William Siemens Elektronische Ressource 18...,"König, Wolfgang",2020,https://doi.org/10.17104/9783406751356,DOCUMENT,ger,9783406751332,Sir William Siemens Elektronische Ressource 18...
1,9783406749360,Johannes Paul II. Elektronische Ressource Der ...,"Drobinski, Matthias",2020,https://doi.org/10.17104/9783406749384,DOCUMENT,ger,9783406749360,Johannes Paul II. Elektronische Ressource Der ...
2,9783406747298,Das wichtigste Wissen Elektronische Ressource ...,"Fischer, Ernst Peter",2020,https://doi.org/10.17104/9783406747311,DOCUMENT,ger,9783406747298,Das wichtigste Wissen Elektronische Ressource ...
3,9783406757808,Polizei- und Ordnungsrecht Elektronische Resso...,"Kingreen, Thorsten",2020,https://doi.org/10.17104/9783406759697,DOCUMENT,ger,9783406757808,Polizei- und Ordnungsrecht Elektronische Resso...
4,9783406745843,Allgemeines Schuldrecht Elektronische Ressourc...,"Brox, Hans",2020,https://doi.org/10.17104/9783406747472,DOCUMENT,ger,9783406745843,Allgemeines Schuldrecht Elektronische Ressourc...
...,...,...,...,...,...,...,...,...,...
2998,9783791046099,Buchführung und Bilanzierung in der Sozialwirt...,"Schwien, Bernd",2020,https://doi.org/10.34156/9783791046112,DOCUMENT,ger,9783791046099,Buchführung und Bilanzierung in der Sozialwirt...
2999,9783800636143,Internationale betriebswirtschaftliche Steuerl...,"Scheffler, Wolfram",2009,https://doi.org/10.15358/9783800644063,DOCUMENT,ger,9783800636143,Internationale betriebswirtschaftliche Steuerl...
3000,9783800637911,The Innovator's Dilemma Elektronische Ressourc...,"Christensen, Clayton M.",2011,https://doi.org/10.15358/9783800642816,DOCUMENT,ger,9783800637911,The Innovator's Dilemma Elektronische Ressourc...
3001,9783791042954,Wirtschaftsthemen verständlich vermitteln Elek...,"Hesse, Nils",2019,https://doi.org/10.34156/9783791042978,DOCUMENT,ger,9783791042954,Wirtschaftsthemen verständlich vermitteln Elek...
3002,9783800634606,Produktionstheorie Elektronische Ressource Joa...,"Schwalbach, Joachim",2008,https://doi.org/10.15358/9783800643943,DOCUMENT,ger,9783800634606,Produktionstheorie Elektronische Ressource Joa...

In [15]:
df_alma_doc = df_alma_doc[['docno', 'text', 'AUTHOR', 'DATE_OF_PUBLICATION', 'URL', 'ELECTRONIC_MATERIAL_TYPE', 'LANGUAGE']]
df_alma_doc

,docno,text,AUTHOR,DATE_OF_PUBLICATION,URL,ELECTRONIC_MATERIAL_TYPE,LANGUAGE
0,9783406751332,Sir William Siemens Elektronische Ressource 18...,"König, Wolfgang",2020,https://doi.org/10.17104/9783406751356,DOCUMENT,ger
1,9783406749360,Johannes Paul II. Elektronische Ressource Der ...,"Drobinski, Matthias",2020,https://doi.org/10.17104/9783406749384,DOCUMENT,ger
2,9783406747298,Das wichtigste Wissen Elektronische Ressource ...,"Fischer, Ernst Peter",2020,https://doi.org/10.17104/9783406747311,DOCUMENT,ger
3,9783406757808,Polizei- und Ordnungsrecht Elektronische Resso...,"Kingreen, Thorsten",2020,https://doi.org/10.17104/9783406759697,DOCUMENT,ger
4,9783406745843,Allgemeines Schuldrecht Elektronische Ressourc...,"Brox, Hans",2020,https://doi.org/10.17104/9783406747472,DOCUMENT,ger
...,...,...,...,...,...,...,...
2998,9783791046099,Buchführung und Bilanzierung in der Sozialwirt...,"Schwien, Bernd",2020,https://doi.org/10.34156/9783791046112,DOCUMENT,ger
2999,9783800636143,Internationale betriebswirtschaftliche Steuerl...,"Scheffler, Wolfram",2009,https://doi.org/10.15358/9783800644063,DOCUMENT,ger
3000,9783800637911,The Innovator's Dilemma Elektronische Ressourc...,"Christensen, Clayton M.",2011,https://doi.org/10.15358/9783800642816,DOCUMENT,ger
3001,9783791042954,Wirtschaftsthemen verständlich vermitteln Elek...,"Hesse, Nils",2019,https://doi.org/10.34156/9783791042978,DOCUMENT,ger
3002,9783800634606,Produktionstheorie Elektronische Ressource Joa...,"Schwalbach, Joachim",2008,https://doi.org/10.15358/9783800643943,DOCUMENT,ger

In [17]:
df_alma_doc = df_alma_doc.rename(columns={"AUTHOR": "Author", "DATE_OF_PUBLICATION": "Pub. Date", "URL": "URL", "ELECTRONIC_MATERIAL_TYPE": "Type", "LANGUAGE": "Language"})
df_alma_doc

,docno,text,Author,Pub. Date,URL,Type,Language
0,9783406751332,Sir William Siemens Elektronische Ressource 18...,"König, Wolfgang",2020,https://doi.org/10.17104/9783406751356,DOCUMENT,ger
1,9783406749360,Johannes Paul II. Elektronische Ressource Der ...,"Drobinski, Matthias",2020,https://doi.org/10.17104/9783406749384,DOCUMENT,ger
2,9783406747298,Das wichtigste Wissen Elektronische Ressource ...,"Fischer, Ernst Peter",2020,https://doi.org/10.17104/9783406747311,DOCUMENT,ger
3,9783406757808,Polizei- und Ordnungsrecht Elektronische Resso...,"Kingreen, Thorsten",2020,https://doi.org/10.17104/9783406759697,DOCUMENT,ger
4,9783406745843,Allgemeines Schuldrecht Elektronische Ressourc...,"Brox, Hans",2020,https://doi.org/10.17104/9783406747472,DOCUMENT,ger
...,...,...,...,...,...,...,...
2998,9783791046099,Buchführung und Bilanzierung in der Sozialwirt...,"Schwien, Bernd",2020,https://doi.org/10.34156/9783791046112,DOCUMENT,ger
2999,9783800636143,Internationale betriebswirtschaftliche Steuerl...,"Scheffler, Wolfram",2009,https://doi.org/10.15358/9783800644063,DOCUMENT,ger
3000,9783800637911,The Innovator's Dilemma Elektronische Ressourc...,"Christensen, Clayton M.",2011,https://doi.org/10.15358/9783800642816,DOCUMENT,ger
3001,9783791042954,Wirtschaftsthemen verständlich vermitteln Elek...,"Hesse, Nils",2019,https://doi.org/10.34156/9783791042978,DOCUMENT,ger
3002,9783800634606,Produktionstheorie Elektronische Ressource Joa...,"Schwalbach, Joachim",2008,https://doi.org/10.15358/9783800643943,DOCUMENT,ger

In [18]:
index_folder = "/home/tim/Schreibtisch/2024-25-Data_Librarian-Reschop_Tim/Modul_2-1/alma_index" #anlegen eines Speicherortes für unseres Index/Dokumentenrepräsentation

indexer = pt.DFIndexer(index_folder, overwrite=True) #DataFrameIndexer für die Indexierung auswählen und festlegen wo er gespeichert werden soll und das ein bereits bestehender Index überschrieben werden soll
index_ref = indexer.index(df_alma_doc['text'], df_alma_doc['docno']) #Festlegen, aus welchen Spalten des DF der Index erstellt wird

#Dieser Code erstellt einen IR-Index (Information Retrieval Index) aus dem DataFrame df_bibsonomy. 
#Die Spalte text enthält die Dokumentinhalte, die indexiert werden, und docno wird als eindeutige ID für jedes Dokument verwendet. 
#Mit diesem Index kannst du später Suchanfragen ausführen oder andere IR-Operationen mit PyTerrier durchführen.

print(f"path to our index: {index_ref.toString()}")

/tmp/ipykernel_3420/3376689978.py:3: DeprecationWarning: Call to deprecated class DFIndexer. (use pt.terrier.IterDictIndexer().index(dataframe.to_dict(orient='records')) instead) -- Deprecated since version 0.11.0.
  indexer = pt.DFIndexer(index_folder, overwrite=True) #DataFrameIndexer für die Indexierung auswählen und festlegen wo er gespeichert werden soll und das ein bereits bestehender Index überschrieben werden soll

path to our index: /home/tim/Schreibtisch/2024-25-Data_Librarian-Reschop_Tim/Modul_2-1/alma_index/data.properties

In [19]:
#Index-Instanz aus der zuvor erstellten Index-Referenz (index_ref) erstellen
#pt.IndexFactory: Eine Klasse in PyTerrier, die verwendet wird, um mit Indexen zu arbeiten (z. B. erstellen, laden, verwenden).
#.of(index_ref): Diese Methode erstellt ein Indexobjekt aus der Referenz (index_ref), die auf den Speicherort des Index zeigt.
#Das zurückgegebene Objekt (index) ermöglicht es dir, auf den Index zuzugreifen und Operationen wie Suchen, Abrufen von Metadaten oder Statistiken auszuführen.

index = pt.IndexFactory.of(index_ref)

#Der zuvor erstellte Index (index_ref) ist lediglich ein Verweis auf den Speicherort des Index (normalerweise ein Ordner auf der Festplatte). 
#Mit pt.IndexFactory.of() wird dieser Verweis "geladen" und als voll funktionsfähiger Index bereitgestellt.
#Erst jetzt haben wir einen Index

In [20]:
print(index.getCollectionStatistics().toString())

Number of documents: 3003
Number of terms: 8140
Number of postings: 36033
Number of fields: 0
Number of tokens: 36807
Field names: []
Positions:   false

In [21]:
term = "deutsch" 
index.getLexicon()[term].toString() #Gibt die Ergebnisse für einen einzigen Term aus

#Nt = Anzahl der Dokumente, in denen [term] vorkommt
#TF = Wie oft kommt [term] überhaupt vor
#maxTF = Wie oft kommt [term] in einem Dokument maximal vor

'term177 Nt=56 TF=58 maxTF=2 @{0 10313 5}'

In [23]:
term = "nation" 
index.getLexicon()[term].toString() #Gibt die Ergebnisse für einen einzigen Term aus

'term379 Nt=9 TF=10 maxTF=2 @{0 33948 3}'

In [25]:
#Welcher [term] kommt insgesamt am häufigsten vor? #Herausgabe nach Häufigkeit geordnet

alma_tf_dict = {}  #Erstellen eines Dict. Schlüssel=Term , Wert=Anzahl des Vorkommens

for kv in index.getLexicon():
    alma_tf_dict[kv.getKey()] = kv.getValue().frequency


alma_tf_dict_sorted = sorted(alma_tf_dict.items(), key=lambda x: x[1], reverse=True) #Nicht nach alphabetisch sondern die nach Häufigkeit des Terms ordnen

In [26]:
top_terms = 30 #gibt die 30 häufigstens Terme in gestemmter Form aus
alma_tf_dict_sorted[:top_terms]

[('elektronisch', 3005),
 ('ressourc', 3004),
 ('und', 1092),
 ('der', 975),
 ('die', 716),
 ('von', 558),
 ('geschicht', 380),
 ('ein', 333),
 ('hrsg', 292),
 ('de', 289),
 ('da', 247),
 ('im', 205),
 ('mit', 160),
 ('michael', 158),
 ('hrung', 155),
 ('zur', 144),
 ('bi', 138),
 ('han', 122),
 ('thoma', 114),
 ('andrea', 110),
 ('peter', 108),
 ('einf', 103),
 ('manag', 99),
 ('wolfgang', 98),
 ('christian', 97),
 ('den', 92),
 ('wie', 88),
 ('grundlagen', 83),
 ('unternehmen', 78),
 ('inkl', 77)]

In [29]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

stem = stemmer.stem("Geschichte")
stem

'geschicht'

In [30]:
#wie oft kommt das Gestemmte Wort vor?
lexicon = index.getLexicon()
lexicon[stem].getDocumentFrequency()

375

In [48]:

#Funktion zur BErechnung des IDF-Wertes

def get_idf_for_term(term, index):
    lex = index.getLexicon()
    stemmed_term = stemmer.stem(term)
    if not stemmed_term in lex:
        return

    lex_entry = lex[stemmed_term]
    
    df_term = lex_entry.getDocumentFrequency()
    N = index.getCollectionStatistics().numberOfDocuments
    
    #inverse Dokumentenfrequenz
    idf = N/df_term
    #logarithmus, damit die Relevanz nicht proportional berechnet wird
    log_idf = np.emath.logn(10, idf)
    
    return log_idf

In [47]:
get_idf_for_term('deutsch', index)

1.7293673051927805

In [ ]:
#TF-IDF Funktion

def calc_tf_idf(query, docno, index):

In [49]:
search_engine_tfidf = pt.BatchRetrieve(index, wmodel="TF_IDF")

/tmp/ipykernel_3420/2880449899.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  search_engine_tfidf = pt.BatchRetrieve(index, wmodel="TF_IDF")

In [50]:
search_engine_tfidf.search("Geschichte")

    qid  docid          docno  rank     score       query
0     1    630  9783406638152     0  2.186318  Geschichte
1     1    748  9783406640544     1  2.186318  Geschichte
2     1   1189  9783406712920     2  2.186318  Geschichte
3     1   1250  9783406715136     3  2.186318  Geschichte
4     1   1375  9783406470769     4  2.186318  Geschichte
..   ..    ...            ...   ...       ...         ...
370   1   1434  9783406313493   370  1.213579  Geschichte
371   1   1473  9783406492754   371  1.213579  Geschichte
372   1   2165  9783406613531   372  1.213579  Geschichte
373   1   1530  9783406509254   373  1.185811  Geschichte
374   1   2145  9783406551345   374  1.185811  Geschichte

[375 rows x 6 columns]

In [51]:
alma_dict = df_alma_doc.to_dict(orient='records')
alma_dict

[{'docno': '9783406751332',
  'text': 'Sir William Siemens Elektronische Ressource 1823-1883 Wolfgang König',
  'Author': 'König, Wolfgang',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406751356',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406749360',
  'text': 'Johannes Paul II. Elektronische Ressource Der Papst, der aus dem Osten kam Matthias Drobinski, Thomas Urban',
  'Author': 'Drobinski, Matthias',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406749384',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406747298',
  'text': 'Das wichtigste Wissen Elektronische Ressource Vom Urknall bis heute Ernst Peter Fischer',
  'Author': 'Fischer, Ernst Peter',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406747311',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406757808',
  'text': 'Polizei- und Ordnungsrecht Elektronische Ressource mit Versammlungsrecht Thorsten Kingreen, Ralf Poscher, Bodo Pieroth, Bernhard Schlink, Michael Kniesel',
  'Author': 'Kingreen, Thorsten',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406759697',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406745843',
  'text': 'Allgemeines Schuldrecht Elektronische Ressource Hans Brox, Wolf-Dietrich Walker',
  'Author': 'Brox, Hans',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406747472',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406757099',
  'text': 'Manifest für die Tiere Elektronische Ressource Corine Pelluchon',
  'Author': 'Pelluchon, Corine',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406757112',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406739538',
  'text': 'Nietzsches Vermächtnis Elektronische Ressource Ecce homo und Der Antichrist Heinrich Meier',
  'Author': 'Meier, Heinrich',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406739545',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406749858',
  'text': 'Acht Tage im Mai Elektronische Ressource Die letzte Woche des Dritten Reiches Volker Ullrich',
  'Author': 'Ullrich, Volker',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406749872',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406748943',
  'text': 'Das neue Unbehagen an der Erinnerungskultur Elektronische Ressource Eine Intervention Aleida Assmann',
  'Author': 'Assmann, Aleida',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406748967',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406745454',
  'text': 'Strafrecht Besonderer Teil II Elektronische Ressource Delikte gegen die Person und die Allgemeinheit Rudolf Rengier',
  'Author': 'Rengier, Rudolf',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406746789',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406739569',
  'text': 'Resilienz Elektronische Ressource Die psychische Widerstandskraft Rebecca Böhme',
  'Author': 'Böhme, Rebecca',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406739576',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406747717',
  'text': 'Schriften zu Kunst und Film Elektronische Ressource hrsg. von Guenther Anders, Reinhard Ellensohn, Kerstin Putz',
  'Author': 'Anders, Guenther',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406747724',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406755989',
  'text': 'Die seltsamsten Orte der Religionen Elektronische Ressource Von versteckten Kirchen, magischen Bäumen und verbotenen Schreinen Johann Hinrich Claussen',
  'Author': 'Claussen, Johann Hinrich',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406756009',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406732294',
  'text': 'Russisches Roulette Elektronische Ressource Vom Kalten Krieg zum Kalten Frieden Horst Teltschik',
  'Author': 'Teltschik, Horst',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406732300',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406741715',
  'text': 'Eskimoland Elektronische Ressource Ein Bericht aus der Arktis Niko Tinbergen',
  'Author': 'Tinbergen, Niko',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406741722',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406756016',
  'text': 'Jesus Elektronische Ressource Leben und Wirkung Jens Schröter',
  'Author': 'Schröter, Jens',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406756030',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783648086858',
  'text': 'Erfassung und Bewertung kommunalen Vermögens in Bayern - inkl. Arbeitshilfen online Elektronische Ressource Leitfaden zur Bewertungsrichtlinie und zur Kommunalen Haushaltsverordnung (Doppik) Horst Körner, Monika Huber',
  'Author': 'Körner, Horst',
  'Pub. Date': 2017,
  'URL': 'https://doi.org/10.34157/9783648086865',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406741388',
  'text': 'Werte und Mächte Elektronische Ressource Eine Geschichte der westlichen Welt Heinrich August Winkler',
  'Author': 'Winkler, Heinrich August',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406741395',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406736971',
  'text': 'Sachenrecht Elektronische Ressource Manfred Wolf, Marina Wellenhofer',
  'Author': 'Wolf, Manfred',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406746253',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406733512',
  'text': 'Öffentliches Baurecht Elektronische Ressource mit verwaltungsprozessualen und staathaftungsrechtlichen Bezügen Martin Will',
  'Author': 'Will, Martin',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406747243',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406754791',
  'text': 'Demokratie Elektronische Ressource Eine deutsche Affäre Hedwig Richter',
  'Author': 'Richter, Hedwig',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406754814',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406740053',
  'text': 'Der Preis des Ruhms Elektronische Ressource Eine Weltgeschichte des Siebenjährigen Krieges Marian Füssel',
  'Author': 'Füssel, Marian',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406740060',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406740091',
  'text': 'Christenverfolgung in der Antike Elektronische Ressource Wolfram Kinzig',
  'Author': 'Kinzig, Wolfram',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406740107',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406750250',
  'text': 'Die NSDAP Elektronische Ressource Von der Gründung bis zum Ende des Dritten Reiches Hans-Ulrich Thamer',
  'Author': 'Thamer, Hans-Ulrich',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406750274',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406750373',
  'text': 'Fürsten im Fadenkreuz Elektronische Ressource Geheimoperationen im Zeitalter der Ritter 1100-1550 Yuval Noah Harari',
  'Author': 'Harari, Yuval Noah',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406750397',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406757525',
  'text': 'Militärgeschichte des Mittelalters Elektronische Ressource Martin Clauss',
  'Author': 'Clauss, Martin',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406757549',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406745096',
  'text': 'Deutsches und Europäisches Verfassungsrecht I Elektronische Ressource Prinzipien, Institutionen, Verfahren Gernot Sydow, Fabian Wittreck',
  'Author': 'Sydow, Gernot',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406765759',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406733802',
  'text': 'Der europäische Traum Elektronische Ressource Vier Lehren aus der Geschichte Aleida Assmann',
  'Author': 'Assmann, Aleida',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406751943',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406758362',
  'text': 'Die Indianer Elektronische Ressource Geschichte der indigenen Nationen in den USA Heike Bungert',
  'Author': 'Bungert, Heike',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406758386',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406735318',
  'text': 'Der Pakt Elektronische Ressource Stalin, Hitler und die Geschichte einer mörderischen Allianz Claudia Weber',
  'Author': 'Weber, Claudia',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406735325',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406739880',
  'text': 'Diese Wahrheiten Elektronische Ressource Eine Geschichte der Vereinigten Staaten von Amerika Jill Lepore',
  'Author': 'Lepore, Jill',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406739897',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406738166',
  'text': 'Demokratie Elektronische Ressource Geschichte, Formen, Theorien Hans Vorländer',
  'Author': 'Vorländer, Hans',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406738173',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406750946',
  'text': 'Vom Sterben Elektronische Ressource Zehn Meditationen zur spirituell-palliativen Praxis Michael Brück',
  'Author': 'Brück, Michael',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406760587',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406737671',
  'text': 'Kleine jüdische Geschichte Elektronische Ressource Michael Brenner',
  'Author': 'Brenner, Michael',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406738159',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406753084',
  'text': 'Betriebsverfassungsrecht Elektronische Ressource Markus Stoffels, Mark Lembke, Gerrick Hoyningen-Huene',
  'Author': 'Stoffels, Markus',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406759444',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406749414',
  'text': 'Beethoven Elektronische Ressource Der einsame Revolutionär Jan Caeyers',
  'Author': 'Caeyers, Jan',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406749438',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406740268',
  'text': 'Grundgesetz Elektronische Ressource Studienkommentar Christoph Gröpl, Kay Windthorst, Christian Coelln',
  'Author': 'Gröpl, Christoph',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406746833',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406739675',
  'text': 'Der Briefschreiber Goethe Elektronische Ressource Albrecht Schöne',
  'Author': 'Schöne, Albrecht',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406743191',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406739422',
  'text': 'Morgen ist da Elektronische Ressource Reden Navid Kermani',
  'Author': 'Kermani, Navid',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406739439',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406733710',
  'text': 'Der Spracherwerb des Kindes Elektronische Ressource Verlauf und Störungen Jürgen Dittmann',
  'Author': 'Dittmann, Jürgen',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406733727',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406745089',
  'text': 'Internationales Wirtschaftsrecht Elektronische Ressource Matthias Herdegen',
  'Author': 'Herdegen, Matthias',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406761904',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406735332',
  'text': 'Vormärz Elektronische Ressource Deutschlands Aufbruch in die Moderne Wilhelm Bleek',
  'Author': 'Bleek, Wilhelm',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406735349',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406756740',
  'text': 'Auschwitz Elektronische Ressource Geschichte und Nachgeschichte Sybille Steinbacher',
  'Author': 'Steinbacher, Sybille',
  'Pub. Date': 2004,
  'URL': 'https://doi.org/10.17104/9783406756764',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406739514',
  'text': 'Espresso mit Archimedes Elektronische Ressource Unglaubliche Geschichten aus der Welt der Mathematik Stefan Buijsman',
  'Author': 'Buijsman, Stefan',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406739521',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406752841',
  'text': 'Hexen Elektronische Ressource Glaube, Verfolgung, Vermarktung Wolfgang Behringer',
  'Author': 'Behringer, Wolfgang',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406752865',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406736339',
  'text': 'Apologie des Sokrates Elektronische Ressource Platon',
  'Author': 'Platon,',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406737664',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406755453',
  'text': 'Maos langer Schatten Elektronische Ressource Chinas Umgang mit der Vergangenheit Daniel Leese',
  'Author': 'Leese, Daniel',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406755477',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406755811',
  'text': 'Spiel der Könige Elektronische Ressource Das Haus Plantagenet und der lange Kampf um Englands Thron Dan Jones',
  'Author': 'Jones, Dan',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406755835',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406741494',
  'text': 'Archipel der Leidenschaften Elektronische Ressource Kleine Philosophie der großen Gefühle Charlotte Casiraghi, Robert Maggiori',
  'Author': 'Casiraghi, Charlotte',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406741500',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406737275',
  'text': 'Recht in der Pflege Elektronische Ressource Lernen, Verstehen, Anwenden Thomas Weiß',
  'Author': 'Weiß, Thomas',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406759895',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406750878',
  'text': 'Das gespaltene Land Elektronische Ressource Ein Psychogramm Hans-Joachim Maaz',
  'Author': 'Maaz, Hans-Joachim',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406753565',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406758027',
  'text': 'Ungarn in der Nußschale Elektronische Ressource Ein Jahrtausend und dreißig Jahre György Dalos',
  'Author': 'Dalos, György',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406758041',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406756191',
  'text': 'Deutschland Elektronische Ressource Globalgeschichte einer Nation hrsg. von Andreas Fahrmeir',
  'Author': 'Fahrmeir, Andreas',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406756214',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406741777',
  'text': 'New Dark Age Elektronische Ressource Der Sieg der Technologie und das Ende der Zukunft James Bridle',
  'Author': 'Bridle, James',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406741784',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406741074',
  'text': 'Verdammtes Licht Elektronische Ressource Der Katholizismus und die Aufklärung Hubert Wolf',
  'Author': 'Wolf, Hubert',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406741081',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406761836',
  'text': 'Juristen jüdischer Herkunft im Kaiserreich und in der Weimarer Republik Elektronische Ressource Peter Landau',
  'Author': 'Landau, Peter',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406761850',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406736537',
  'text': 'Geschichte Frankreichs im 20. Jahrhundert Elektronische Ressource Matthias Waechter',
  'Author': 'Waechter, Matthias',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406736544',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406757068',
  'text': 'America First Elektronische Ressource Donald Trump im Weißen Haus Stephan Bierling',
  'Author': 'Bierling, Stephan',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406757082',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406762895',
  'text': 'Staatsrecht III Elektronische Ressource Bezüge zum Völker- und Europarecht Christian Calliess',
  'Author': 'Calliess, Christian',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406768019',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406748806',
  'text': 'Völkerrecht Elektronische Ressource Matthias Herdegen',
  'Author': 'Herdegen, Matthias',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406748813',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406736490',
  'text': 'Vincent van Gogh Elektronische Ressource Uwe M. Schneede',
  'Author': 'Schneede, Uwe M.',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406736506',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406736100',
  'text': 'Die Perserkriege Elektronische Ressource Wolfgang Will',
  'Author': 'Will, Wolfgang',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406736117',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406756481',
  'text': 'Die Regenschirm-Formel Elektronische Ressource oder Die Kunst, die Welt mit klarem Verstand zu betrachten Mickaël Launay',
  'Author': 'Launay, Mickaël',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406756504',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406748998',
  'text': 'Karl V. Elektronische Ressource Der Kaiser, dem die Welt zerbrach Heinz Schilling',
  'Author': 'Schilling, Heinz',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406749018',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406736476',
  'text': 'Geschichte der Globalisierung Elektronische Ressource Dimensionen, Prozesse, Epochen Jürgen Osterhammel, Niels P. Petersson',
  'Author': 'Osterhammel, Jürgen',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406738449',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406734816',
  'text': 'Die Templer Elektronische Ressource Aufstieg und Untergang von Gottes heiligen Kriegern Dan Jones',
  'Author': 'Jones, Dan',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406734823',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406734359',
  'text': 'Alexander von Humboldt Elektronische Ressource Andreas W. Daum',
  'Author': 'Daum, Andreas W.',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406734366',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406745683',
  'text': 'Novozän Elektronische Ressource Das kommende Zeitalter der Hyperintelligenz James Lovelock, Bryan Appleyard',
  'Author': 'Lovelock, James',
  'Pub. Date': 2020,
  'URL': 'https://doi.org/10.17104/9783406745706',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406742330',
  'text': 'al-Andalus Elektronische Ressource Geschichte des islamischen Spanien Brian A. Catlos',
  'Author': 'Catlos, Brian A.',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406742347',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406741401',
  'text': 'Der Weg in die Unfreiheit Elektronische Ressource Russland, Europa, Amerika Timothy Snyder',
  'Author': 'Snyder, Timothy',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406741418',
  'Type': 'DOCUMENT',
  'Language': 'ger'},
 {'docno': '9783406736063',
  'text': 'Deutsche Kolonialgeschichte Elektronische Ressource Sebastian Conrad',
  'Author': 'Conrad, Sebastian',
  'Pub. Date': 2019,
  'URL': 'https://doi.org/10.17104/9783406736070',
  'Type': 'DOCUMENT',
  'Language': 'ger'},

In [52]:
index_folder_alma = "/home/tim/Schreibtisch/2024-25-Data_Librarian-Reschop_Tim/Modul_2-1/alma_index"

fields=['docno', 'text', 'Author', 'Pub. Date', 'URL', 'Type', 'Language']

indexer_alma = pt.IterDictIndexer(index_folder_alma, meta={'docno': 50, 'text': 200}, fields=True, text_attrs=fields, overwrite=True)
index_ref_alma = indexer_alma.index(alma_dict)

print(f"path to our index: {index_ref_alma.toString()}")

path to our index: /home/tim/Schreibtisch/2024-25-Data_Librarian-Reschop_Tim/Modul_2-1/alma_index/data.properties

In [54]:
index_alma = pt.IndexFactory.of(index_ref_alma)
print(index_alma.getCollectionStatistics().toString())

Number of documents: 3003
Number of terms: 8140
Number of postings: 36034
Number of fields: 7
Number of tokens: 36808
Field names: [docno, text, Author, Pub. Date, URL, Type, Language]
Positions:   false

In [55]:
search_engine_alma = pt.terrier.Retriever(index_alma, wmodel="TF_IDF")

In [56]:
res = search_engine_alma.search("deutsch")
res

   qid  docid          docno  rank     score    query
0    1    691  9783406656309     0  4.162160  deutsch
1    1     70  9783406736063     1  3.979053  deutsch
2    1   1195  9783406729584     2  3.979053  deutsch
3    1   1250  9783406715136     3  3.979053  deutsch
4    1   2140  9783406562488     4  3.979053  deutsch
5    1   2239  9783406536281     5  3.817988  deutsch
6    1   1992  9783648120255     6  3.675582  deutsch
7    1     20  9783406754791     7  3.669455  deutsch
8    1   1752  9783406480072     8  3.669455  deutsch
9    1    471  9783406661068     9  3.532046  deutsch
10   1   1572  9783406447655    10  3.532046  deutsch
11   1   2249  9783406621147    11  3.532046  deutsch
12   1   2338  9783406587955    12  3.532046  deutsch
13   1   2466  9783406675072    13  3.532046  deutsch
14   1    610  9783406640612    14  3.404557  deutsch
15   1    640  9783406647604    15  3.404557  deutsch
16   1    805  9783406646157    16  3.404557  deutsch
17   1    980  9783406721410    17  3.404557  deutsch
18   1   1045  9783406707711    18  3.404557  deutsch
19   1   2110  9783406557316    19  3.404557  deutsch
20   1   2157  9783406624148    20  3.404557  deutsch
21   1   2176  9783406535970    21  3.404557  deutsch
22   1   2220  9783406562624    22  3.404557  deutsch
23   1   2399  9783406622519    23  3.285951  deutsch
24   1    563  9783406667046    24  3.175330  deutsch
25   1    564  9783406655777    25  3.175330  deutsch
26   1    573  9783406654466    26  3.175330  deutsch
27   1   1162  9783406713873    27  3.175330  deutsch
28   1   2197  9783406616457    28  3.175330  deutsch
29   1   2855  9783791041506    29  3.175330  deutsch
30   1    204  9783406737077    30  3.071915  deutsch
31   1    507  9783406655784    31  3.071915  deutsch
32   1    551  9783406654480    32  3.071915  deutsch
33   1   1050  9783406726354    33  3.071915  deutsch
34   1   2111  9783406622922    34  3.071915  deutsch
35   1   2272  9783406612268    35  3.071915  deutsch
36   1     26  9783406745096    36  2.975023  deutsch
37   1    105  9783406732874    37  2.975023  deutsch
38   1    549  9783406655791    38  2.975023  deutsch
39   1   1075  9783406708022    39  2.975023  deutsch
40   1    794  9783406644955    40  2.884057  deutsch
41   1    959  9783954662449    41  2.884057  deutsch
42   1   1053  9783406719691    42  2.884057  deutsch
43   1   2452  9783406679032    43  2.884057  deutsch
44   1    491  9783406667664    44  2.798488  deutsch
45   1    868  9783406660504    45  2.569758  deutsch
46   1    132  9783406753381    46  2.501603  deutsch
47   1   1998  9783769137064    47  2.501603  deutsch
48   1   2079  9783791038490    48  2.501603  deutsch
49   1   2797  9783791048284    49  2.501603  deutsch
50   1   1646  9783800653980    50  2.436970  deutsch
51   1   2372  9783406630460    51  2.436970  deutsch
52   1   2545  9783406683572    52  2.375593  deutsch
53   1    786  9783406660498    53  2.317231  deutsch
54   1   2145  9783406551345    54  2.158170  deutsch
55   1    275  9783406739972    55  2.019544  deutsch

In [58]:
pickle.dump(df_alma_doc, open("/home/tim/Schreibtisch/2024-25-Data_Librarian-Reschop_Tim/Modul_2-1/alma_index/alma_beck.pkl", "wb"))