In [25]:
import json
import pandas as pd

In [26]:
data_terror = json.load(open("/home/tim/Documents/terrorismus.json"))
data_extrem = json.load(open("/home/tim/Documents/extremism.json"))
data_islam = json.load(open("/home/tim/Documents/Islamism.json"))

In [27]:
data_terror.keys()

dict_keys(['types', 'properties', 'items'])

In [28]:
df_terror = pd.DataFrame(data_terror["items"])
df_extrem = pd.DataFrame(data_extrem["items"])
df_islam = pd.DataFrame(data_islam["items"])

In [29]:
df_terror

,type,id,tags,intraHash,label,user,description,date,changeDate,count,...,medline-pst,journaltitle,citeulike-linkout-10,venue,slides,pdf,__markedentry,ean,asin,dewey
0,Bookmark,https://www.bibsonomy.org/url/557355769d542ef8...,"[Terrorismus, Extremismus, Politische_Bildung]",557355769d542ef805d5d9ab57e876a7,"Ideologie – Radikalismus, Extremismus und Terr...",as,,2023-05-21 17:32:37,2023-05-21 17:32:37,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bookmark,https://www.bibsonomy.org/url/e7915b4fa2ee1faa...,"[Irak, Terrorismus, Afghanistan, IS, Islamismus]",e7915b4fa2ee1faac19b8e28fe229d3e,Terrorismus: BBC-Statistik zu Dschihadisten - ...,as,,2014-12-14 01:31:10,2014-12-14 01:31:10,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bookmark,https://www.bibsonomy.org/url/748153e9fa42c2b8...,"[Argumentationstraining, Gruppenbezogene_Mensc...",748153e9fa42c2b8ab0577584f6e6275,Der Einzeltäter im Terrorismus | bpb,as,,2020-03-12 13:14:00,2020-03-12 13:14:00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bookmark,https://www.bibsonomy.org/url/c1edff85e1df81a7...,"[Argumentationstraining, Terrorismus, Hildeshe...",c1edff85e1df81a7324e04f0a1cd5486,„Muslime töten“? Terrorismus-Anklage gegen Hil...,as,,2020-09-29 23:17:17,2020-09-29 23:17:17,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bookmark,https://www.bibsonomy.org/url/f7b4f4c0856d23df...,"[GeistigesEigentum, Innovation, LW1, OpenSourc...",f7b4f4c0856d23dfb62c08e5698bcab4,heise online -Sun-Manager bezichtigt Microsoft...,torstenschuenemann,"Sun-Manager bezichtigt Microsoft des ""Patent-T...",2007-07-24 22:45:01,2008-06-01 22:13:30,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,Publication,https://www.bibsonomy.org/bibtex/284c2b841fa1f...,"[complexity, modeling, system, complex-adaptiv...",84c2b841fa1f8f493b5f59812d27e6fd,Simulating Complex Social Behaviour with the G...,jrennstich,,2010-03-10 21:32:34,2010-03-10 21:32:34,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1684,Publication,https://www.bibsonomy.org/bibtex/2069376423855...,"[ville, modèle, urbanisme, afrique, sociologie]",069376423855da8fc60b3e8087dcbbc8,Le Stade Dubaï du capitalisme,app,"Mike Davis né en 1946, est un sociologue améri...",2015-05-11 02:23:27,2015-05-11 02:27:29,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1685,Publication,https://www.bibsonomy.org/bibtex/2cbb739feecc7...,"[Procedings, Transformative_Learning, Krise, t...",cbb739feecc72ebe78416990c697489e,Transformative Learning in Time of Crisis:\r\n...,tl-now,LIST OF PAPERS\r\nKeynote Lecture................,2022-04-22 18:14:10,2022-04-22 18:14:10,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1686,Publication,https://www.bibsonomy.org/bibtex/2cbb739feecc7...,"[Procedings, Transformative_Learning, Conference]",cbb739feecc72ebe78416990c697489e,Transformative Learning in Time of Crisis:\r\n...,3viertelgeist,LIST OF PAPERS\r\nKeynote Lecture................,2016-10-18 22:35:28,2022-04-22 14:53:24,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1687,Publication,https://www.bibsonomy.org/bibtex/250415633ed41...,"[geography, globalization, comics, priorität:3...",50415633ed41686c1a28affac968f60e,Manga world: Globalization theory revisited,iglesia,,2009-12-11 17:36:29,2009-12-11 17:36:29,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df_terror_edit = df_terror[["label", "author", "year", "type"]] #neuer DF mit weniger Spalten

In [31]:
df_terror_edit

,label,author,year,type
0,"Ideologie – Radikalismus, Extremismus und Terr...",NaN,NaN,Bookmark
1,Terrorismus: BBC-Statistik zu Dschihadisten - ...,NaN,NaN,Bookmark
2,Der Einzeltäter im Terrorismus | bpb,NaN,NaN,Bookmark
3,„Muslime töten“? Terrorismus-Anklage gegen Hil...,NaN,NaN,Bookmark
4,heise online -Sun-Manager bezichtigt Microsoft...,NaN,NaN,Bookmark
...,...,...,...,...
1683,Simulating Complex Social Behaviour with the G...,"[Thorsten Chmura, Johannes Kaiser, Thomas Pitz]",2007,Publication
1684,Le Stade Dubaï du capitalisme,[Mike Davis],2007,Publication
1685,Transformative Learning in Time of Crisis:\r\n...,NaN,2011,Publication
1686,Transformative Learning in Time of Crisis:\r\n...,NaN,2011,Publication
1687,Manga world: Globalization theory revisited,[P. J. Rimmer],2004,Publication

In [32]:
#Bereinigung des Datensatzes
df_terror_edit = df_terror_edit.loc[df_terror_edit["author"].isnull() == False] #alle NaN in Spalte "author" entfernen
df_terror_edit.loc[df_terror_edit.type == "Publication"] #in der Spalte "type" nur "Publication" anzeigen
df_terror_edit = df_terror_edit.drop_duplicates(subset = "label", keep = "first") #Entfernen von Duplikaten
df_terror_edit

,label,author,year,type
1000,Die Fiktion „Internationaler Terrorismus“,[Elias Davidsson],2017,Publication
1001,Islam und Terrorismus : was der Koran wirklich...,[Mark A. Gabriel],2004,Publication
1002,"Clausewitz, Guerillakrieg und Terrorismus. Zur...","[Christopher Daase, Sebastian Schindler]",2009,Publication
1003,Cyber-Terrorismus,[Stefan Schumacher],2014,Publication
1005,Terrorismus in der Bundesrepublik der Siebzige...,[Klaus Weinhauer],2004,Publication
...,...,...,...,...
1681,"SARFT, MII Co-Issue Online Video Regulation",[ Marbridgeconsulting],20071229,Publication
1682,The Design of Dissent: Socially and Politicall...,[Milton Glaser],2006,Publication
1683,Simulating Complex Social Behaviour with the G...,"[Thorsten Chmura, Johannes Kaiser, Thomas Pitz]",2007,Publication
1684,Le Stade Dubaï du capitalisme,[Mike Davis],2007,Publication
1687,Manga world: Globalization theory revisited,[P. J. Rimmer],2004,Publication

In [33]:
#Hinzufügen einer neuen Spalte mit Suchbegriff "Terrorismus"
df_terror_edit["search_term"] = "Terrorismus"
df_terror_edit

,label,author,year,type,search_term
1000,Die Fiktion „Internationaler Terrorismus“,[Elias Davidsson],2017,Publication,Terrorismus
1001,Islam und Terrorismus : was der Koran wirklich...,[Mark A. Gabriel],2004,Publication,Terrorismus
1002,"Clausewitz, Guerillakrieg und Terrorismus. Zur...","[Christopher Daase, Sebastian Schindler]",2009,Publication,Terrorismus
1003,Cyber-Terrorismus,[Stefan Schumacher],2014,Publication,Terrorismus
1005,Terrorismus in der Bundesrepublik der Siebzige...,[Klaus Weinhauer],2004,Publication,Terrorismus
...,...,...,...,...,...
1681,"SARFT, MII Co-Issue Online Video Regulation",[ Marbridgeconsulting],20071229,Publication,Terrorismus
1682,The Design of Dissent: Socially and Politicall...,[Milton Glaser],2006,Publication,Terrorismus
1683,Simulating Complex Social Behaviour with the G...,"[Thorsten Chmura, Johannes Kaiser, Thomas Pitz]",2007,Publication,Terrorismus
1684,Le Stade Dubaï du capitalisme,[Mike Davis],2007,Publication,Terrorismus
1687,Manga world: Globalization theory revisited,[P. J. Rimmer],2004,Publication,Terrorismus

In [34]:
#Umbenennen der Spalten zur besseren Lesbarkeit über ein Dict
df_terror_edit = df_terror_edit.rename(columns={"label": "Title", "author": "Authors", "year": "Year", "type": "Type", "search_term": "Search Term"})
df_terror_edit

,Title,Authors,Year,Type,Search Term
1000,Die Fiktion „Internationaler Terrorismus“,[Elias Davidsson],2017,Publication,Terrorismus
1001,Islam und Terrorismus : was der Koran wirklich...,[Mark A. Gabriel],2004,Publication,Terrorismus
1002,"Clausewitz, Guerillakrieg und Terrorismus. Zur...","[Christopher Daase, Sebastian Schindler]",2009,Publication,Terrorismus
1003,Cyber-Terrorismus,[Stefan Schumacher],2014,Publication,Terrorismus
1005,Terrorismus in der Bundesrepublik der Siebzige...,[Klaus Weinhauer],2004,Publication,Terrorismus
...,...,...,...,...,...
1681,"SARFT, MII Co-Issue Online Video Regulation",[ Marbridgeconsulting],20071229,Publication,Terrorismus
1682,The Design of Dissent: Socially and Politicall...,[Milton Glaser],2006,Publication,Terrorismus
1683,Simulating Complex Social Behaviour with the G...,"[Thorsten Chmura, Johannes Kaiser, Thomas Pitz]",2007,Publication,Terrorismus
1684,Le Stade Dubaï du capitalisme,[Mike Davis],2007,Publication,Terrorismus
1687,Manga world: Globalization theory revisited,[P. J. Rimmer],2004,Publication,Terrorismus

In [35]:
#Selber Ablauf für die anderen beiden DF

#df_extrem
df_extrem_edit = df_extrem[["label", "author", "year", "type"]]
df_extrem_edit = df_extrem_edit.loc[df_extrem_edit["author"].isnull() == False] #alle NaN in Spalte "author" entfernen
df_extrem_edit.loc[df_extrem_edit.type == "Publication"] #in der Spalte "type" nur "Publication" anzeigen
df_extrem_edit = df_extrem_edit.drop_duplicates(subset = "label", keep = "first") #Entfernen von Duplikaten
df_extrem_edit["search_term"] = "Extremism" #Neue Spalte mit Suchbegriff
df_extrem_edit = df_extrem_edit.rename(columns={"label": "Title", "author": "Authors", "year": "Year", "type": "Type", "search_term": "Search Term"}) #Umbenennen der Spalten

#df_islam

df_islam_edit = df_islam[["label", "author", "year", "type"]]
df_islam_edit = df_islam_edit.loc[df_islam_edit["author"].isnull() == False] #alle NaN in Spalte "author" entfernen
df_islam_edit.loc[df_islam_edit.type == "Publication"] #in der Spalte "type" nur "Publication" anzeigen
df_islam_edit = df_islam_edit.drop_duplicates(subset = "label", keep = "first") #Entfernen von Duplikaten
df_islam_edit["search_term"] = "Islamism" #Neue Spalte mit Suchbegriff
df_islam_edit = df_islam_edit.rename(columns={"label": "Title", "author": "Authors", "year": "Year", "type": "Type", "search_term": "Search Term"}) #Umbenennen der Spalten


df_islam_edit

,Title,Authors,Year,Type,Search Term
528,Islamism and the recolonization of Algeria.(Be...,[Marnia Lazreg],1998,Publication,Islamism
529,Secular vs. Islamist Polarization in Egypt on ...,"[Ingmar Weber, Venkata R. Kiran Garimella, Ala...",2013,Publication,Islamism
530,Diffusion in Networks: The Strategic Spread of...,"[Maureen Boyce, Mark Byrne, Erin Dorpinghaus, ...",2016,Publication,Islamism
531,The Global Spread of Islamism: An Agent-Based ...,"[Morgan L. Eichman, James A. Rolfsen, Mark J. ...",2014,Publication,Islamism
532,The origins of liberalism and islamism in the ...,[Necmettin Do an],2006,Publication,Islamism
...,...,...,...,...,...
1311,Mononuclear nickel(II) complexes coordinated b...,"[Hassan Hadadzadeh, Ghobad Mansouri, Ali Rezva...",{2011},Publication,Islamism
1312,"Synthesis, characterization, crystal structure...","[Robabeh Alizadeh, Salma Hafezeffati, Vahid Am...",{2015},Publication,Islamism
1313,"Syntheses, crystal, molecular structures, and ...","[M. Mirzaei, H. Eshtiagh-Hosseini, N. Alfi, H....",{2011},Publication,Islamism
1314,La città ineguale. Pratiche culturali e organi...,[ a cura di Cattedra e Memoli],1999,Publication,Islamism
1315,"Global incidence, prevalence, years lived with...","[Alize J Ferrari, Damian Francesco Santomauro,...",2024,Publication,Islamism

In [36]:
df_extrem_edit

,Title,Authors,Year,Type,Search Term
224,German Trade Unions and Right Extremism: Under...,[Michael Fichter],2008,Publication,Extremism
226,The Concept of Extremist Text and its Types,[Abror Kurbonmuratov Abdurashidovich],2023,Publication,Extremism
227,"Right""=Wing Extremism in Post""=War Europe",[Klaus von Beyme],1988,Publication,Extremism
228,The role of network topology on extremism prop...,"[Frédéric Amblard, Guillaume Deffuant]",2004,Publication,Extremism
229,"Affinity Towards Right""=Wing Extremism in West...","[Jürgen W. Falter, Siegfried Schumann]",1988,Publication,Extremism
...,...,...,...,...,...
1218,Precision and accuracy of 3D lower extremity r...,"[Paul K. Commean, Kirk E. Smith, Michael W. Va...",1996,Publication,Extremism
1219,Upper Extremity Kinematic Parameters: Referenc...,"[Kunkun Zhao, Chuan Guo, Haibo Bian, Jiyong Yu...",2021,Publication,Extremism
1220,"Collective moderation of hate, toxicity, and e...","[Jana Lasser, Alina Herderich, Joshua Garland,...",2023,Publication,Extremism
1222,The logarithmic average of sample extremes is ...,"[István Berkes, Lajos Horváth]",2001,Publication,Extremism
1223,Extremes and upcrossing intensities for P-diff...,[J. M. P. Albin],2000,Publication,Extremism

In [37]:
#Zusammenführen der DFs

df_complete_1 = pd.concat([df_extrem_edit, df_islam_edit, df_terror_edit])
df_complete_1

,Title,Authors,Year,Type,Search Term
224,German Trade Unions and Right Extremism: Under...,[Michael Fichter],2008,Publication,Extremism
226,The Concept of Extremist Text and its Types,[Abror Kurbonmuratov Abdurashidovich],2023,Publication,Extremism
227,"Right""=Wing Extremism in Post""=War Europe",[Klaus von Beyme],1988,Publication,Extremism
228,The role of network topology on extremism prop...,"[Frédéric Amblard, Guillaume Deffuant]",2004,Publication,Extremism
229,"Affinity Towards Right""=Wing Extremism in West...","[Jürgen W. Falter, Siegfried Schumann]",1988,Publication,Extremism
...,...,...,...,...,...
1681,"SARFT, MII Co-Issue Online Video Regulation",[ Marbridgeconsulting],20071229,Publication,Terrorismus
1682,The Design of Dissent: Socially and Politicall...,[Milton Glaser],2006,Publication,Terrorismus
1683,Simulating Complex Social Behaviour with the G...,"[Thorsten Chmura, Johannes Kaiser, Thomas Pitz]",2007,Publication,Terrorismus
1684,Le Stade Dubaï du capitalisme,[Mike Davis],2007,Publication,Terrorismus
1687,Manga world: Globalization theory revisited,[P. J. Rimmer],2004,Publication,Terrorismus

In [38]:
#Bereinigen von "falschen" Werten
# 1. Year

df_complete_1["Year_correct"] = df_complete_1.apply(lambda row: row.Year.isdigit(), axis=1)
df_complete_1.loc[df_complete_1.Year_correct == False]
df_complete_1 = df_complete_1.loc[df_complete_1.Year_correct == True]

df_complete_1

,Title,Authors,Year,Type,Search Term,Year_correct
224,German Trade Unions and Right Extremism: Under...,[Michael Fichter],2008,Publication,Extremism,True
226,The Concept of Extremist Text and its Types,[Abror Kurbonmuratov Abdurashidovich],2023,Publication,Extremism,True
227,"Right""=Wing Extremism in Post""=War Europe",[Klaus von Beyme],1988,Publication,Extremism,True
228,The role of network topology on extremism prop...,"[Frédéric Amblard, Guillaume Deffuant]",2004,Publication,Extremism,True
229,"Affinity Towards Right""=Wing Extremism in West...","[Jürgen W. Falter, Siegfried Schumann]",1988,Publication,Extremism,True
...,...,...,...,...,...,...
1681,"SARFT, MII Co-Issue Online Video Regulation",[ Marbridgeconsulting],20071229,Publication,Terrorismus,True
1682,The Design of Dissent: Socially and Politicall...,[Milton Glaser],2006,Publication,Terrorismus,True
1683,Simulating Complex Social Behaviour with the G...,"[Thorsten Chmura, Johannes Kaiser, Thomas Pitz]",2007,Publication,Terrorismus,True
1684,Le Stade Dubaï du capitalisme,[Mike Davis],2007,Publication,Terrorismus,True
1687,Manga world: Globalization theory revisited,[P. J. Rimmer],2004,Publication,Terrorismus,True

In [39]:
#Entfernen von Werten in "Year" die nicht mit dem Format YYYY übereinstimmen, also mehr als 4 Zeichen haben

df_complete_1 = df_complete_1[df_complete_1["Year"].str.len() <= 4]
df_complete_1

,Title,Authors,Year,Type,Search Term,Year_correct
224,German Trade Unions and Right Extremism: Under...,[Michael Fichter],2008,Publication,Extremism,True
226,The Concept of Extremist Text and its Types,[Abror Kurbonmuratov Abdurashidovich],2023,Publication,Extremism,True
227,"Right""=Wing Extremism in Post""=War Europe",[Klaus von Beyme],1988,Publication,Extremism,True
228,The role of network topology on extremism prop...,"[Frédéric Amblard, Guillaume Deffuant]",2004,Publication,Extremism,True
229,"Affinity Towards Right""=Wing Extremism in West...","[Jürgen W. Falter, Siegfried Schumann]",1988,Publication,Extremism,True
...,...,...,...,...,...,...
1680,Summarization and information loss in network ...,"[J.F. Olson, K.M. Carley]",2008,Publication,Terrorismus,True
1682,The Design of Dissent: Socially and Politicall...,[Milton Glaser],2006,Publication,Terrorismus,True
1683,Simulating Complex Social Behaviour with the G...,"[Thorsten Chmura, Johannes Kaiser, Thomas Pitz]",2007,Publication,Terrorismus,True
1684,Le Stade Dubaï du capitalisme,[Mike Davis],2007,Publication,Terrorismus,True
1687,Manga world: Globalization theory revisited,[P. J. Rimmer],2004,Publication,Terrorismus,True

In [40]:
#Entfernen von Werten ind "Authors" die nur ein Wort beinhaltet als nicht aus Vor- und Nachname bestehen
def has_full_name(author_list):
    return any(len(name.split()) > 1 for name in author_list)

df_complete_1 = df_complete_1[df_complete_1["Authors"].apply(has_full_name)]
df_complete_1

,Title,Authors,Year,Type,Search Term,Year_correct
224,German Trade Unions and Right Extremism: Under...,[Michael Fichter],2008,Publication,Extremism,True
226,The Concept of Extremist Text and its Types,[Abror Kurbonmuratov Abdurashidovich],2023,Publication,Extremism,True
227,"Right""=Wing Extremism in Post""=War Europe",[Klaus von Beyme],1988,Publication,Extremism,True
228,The role of network topology on extremism prop...,"[Frédéric Amblard, Guillaume Deffuant]",2004,Publication,Extremism,True
229,"Affinity Towards Right""=Wing Extremism in West...","[Jürgen W. Falter, Siegfried Schumann]",1988,Publication,Extremism,True
...,...,...,...,...,...,...
1680,Summarization and information loss in network ...,"[J.F. Olson, K.M. Carley]",2008,Publication,Terrorismus,True
1682,The Design of Dissent: Socially and Politicall...,[Milton Glaser],2006,Publication,Terrorismus,True
1683,Simulating Complex Social Behaviour with the G...,"[Thorsten Chmura, Johannes Kaiser, Thomas Pitz]",2007,Publication,Terrorismus,True
1684,Le Stade Dubaï du capitalisme,[Mike Davis],2007,Publication,Terrorismus,True
1687,Manga world: Globalization theory revisited,[P. J. Rimmer],2004,Publication,Terrorismus,True

In [41]:
#Die Zählung bei 1 Beginnen lassen
df_complete_1.reset_index(drop=True, inplace=True)
df_complete_1.index = df_complete_1.index + 1
df_complete_1

,Title,Authors,Year,Type,Search Term,Year_correct
1,German Trade Unions and Right Extremism: Under...,[Michael Fichter],2008,Publication,Extremism,True
2,The Concept of Extremist Text and its Types,[Abror Kurbonmuratov Abdurashidovich],2023,Publication,Extremism,True
3,"Right""=Wing Extremism in Post""=War Europe",[Klaus von Beyme],1988,Publication,Extremism,True
4,The role of network topology on extremism prop...,"[Frédéric Amblard, Guillaume Deffuant]",2004,Publication,Extremism,True
5,"Affinity Towards Right""=Wing Extremism in West...","[Jürgen W. Falter, Siegfried Schumann]",1988,Publication,Extremism,True
...,...,...,...,...,...,...
2310,Summarization and information loss in network ...,"[J.F. Olson, K.M. Carley]",2008,Publication,Terrorismus,True
2311,The Design of Dissent: Socially and Politicall...,[Milton Glaser],2006,Publication,Terrorismus,True
2312,Simulating Complex Social Behaviour with the G...,"[Thorsten Chmura, Johannes Kaiser, Thomas Pitz]",2007,Publication,Terrorismus,True
2313,Le Stade Dubaï du capitalisme,[Mike Davis],2007,Publication,Terrorismus,True
2314,Manga world: Globalization theory revisited,[P. J. Rimmer],2004,Publication,Terrorismus,True

In [42]:

#Aufsteigend nach Jahr sortierten
df_complete_1 = df_complete_1.sort_values(by="Year")
df_complete_1

,Title,Authors,Year,Type,Search Term,Year_correct
400,Das Extremum der Formänderungsarbeit,[Georg Prange],1916,Publication,Extremism,True
1664,Terrorismus und Kommunismus,[Karl Kautsky],1919,Publication,Terrorismus,True
1403,Das islamische Fremdenrecht bis zu den islam...,[Willi Heffening],1921,Publication,Islamism,True
1436,Kritik der Lehre Leonbards Erfüllungsort Schul...,[Mehmed Férid],1923,Publication,Islamism,True
1162,Hygiene im Lichte des Islams,[Mohamed Abdul Chalik Dalgamoni],1925,Publication,Islamism,True
...,...,...,...,...,...,...
459,Do users adopt extremist beliefs from exposure...,"[Matheus Schmitz, Goran Muric, Daniel Hickey, ...",2024,Publication,Extremism,True
398,Time-varying Extremum Graphs.,"[Somenath Das, Raghavendra Sridharamurthy, Vij...",2024,Publication,Extremism,True
610,Safe Extremum Seeking Applications in Particle...,"[Alan Williams, Alexander Scheinker, En-Chuan ...",2024,Publication,Extremism,True
659,Monitoring the evolution of antisemitic discou...,"[Raza Ul-Mustafa, Nathalie Japkowicz]",2024,Publication,Extremism,True
911,Investigating long short-term memory approach ...,"[Shynar Mussiraliyeva, Milana Bolatbek, Gulsha...",2025,Publication,Extremism,True

In [43]:
#Spalte "Year_correct" entfernen

df_complete_1 = df_complete_1.drop(columns=["Year_correct"])
df_complete_1

,Title,Authors,Year,Type,Search Term
400,Das Extremum der Formänderungsarbeit,[Georg Prange],1916,Publication,Extremism
1664,Terrorismus und Kommunismus,[Karl Kautsky],1919,Publication,Terrorismus
1403,Das islamische Fremdenrecht bis zu den islam...,[Willi Heffening],1921,Publication,Islamism
1436,Kritik der Lehre Leonbards Erfüllungsort Schul...,[Mehmed Férid],1923,Publication,Islamism
1162,Hygiene im Lichte des Islams,[Mohamed Abdul Chalik Dalgamoni],1925,Publication,Islamism
...,...,...,...,...,...
459,Do users adopt extremist beliefs from exposure...,"[Matheus Schmitz, Goran Muric, Daniel Hickey, ...",2024,Publication,Extremism
398,Time-varying Extremum Graphs.,"[Somenath Das, Raghavendra Sridharamurthy, Vij...",2024,Publication,Extremism
610,Safe Extremum Seeking Applications in Particle...,"[Alan Williams, Alexander Scheinker, En-Chuan ...",2024,Publication,Extremism
659,Monitoring the evolution of antisemitic discou...,"[Raza Ul-Mustafa, Nathalie Japkowicz]",2024,Publication,Extremism
911,Investigating long short-term memory approach ...,"[Shynar Mussiraliyeva, Milana Bolatbek, Gulsha...",2025,Publication,Extremism

In [44]:
#Zuletzt löschen von allen möglichen Zeilen in denen möglicherweise NaN vorkommt (es gab keine)

df_complete_1 = df_complete_1.dropna()
df_complete_1

,Title,Authors,Year,Type,Search Term
400,Das Extremum der Formänderungsarbeit,[Georg Prange],1916,Publication,Extremism
1664,Terrorismus und Kommunismus,[Karl Kautsky],1919,Publication,Terrorismus
1403,Das islamische Fremdenrecht bis zu den islam...,[Willi Heffening],1921,Publication,Islamism
1436,Kritik der Lehre Leonbards Erfüllungsort Schul...,[Mehmed Férid],1923,Publication,Islamism
1162,Hygiene im Lichte des Islams,[Mohamed Abdul Chalik Dalgamoni],1925,Publication,Islamism
...,...,...,...,...,...
459,Do users adopt extremist beliefs from exposure...,"[Matheus Schmitz, Goran Muric, Daniel Hickey, ...",2024,Publication,Extremism
398,Time-varying Extremum Graphs.,"[Somenath Das, Raghavendra Sridharamurthy, Vij...",2024,Publication,Extremism
610,Safe Extremum Seeking Applications in Particle...,"[Alan Williams, Alexander Scheinker, En-Chuan ...",2024,Publication,Extremism
659,Monitoring the evolution of antisemitic discou...,"[Raza Ul-Mustafa, Nathalie Japkowicz]",2024,Publication,Extremism
911,Investigating long short-term memory approach ...,"[Shynar Mussiraliyeva, Milana Bolatbek, Gulsha...",2025,Publication,Extremism

In [45]:
#DF als JSON exportieren
df_complete_1.to_json("Bibsonomy_List.json", orient="records") #Was bedeutet orient?

In [46]:
#Überprüfen ob es geklappt hat
with open ("Bibsonomy_List.json", "r") as f:
    j_load = json.load(f)
    print(json.dumps(j_load, indent=2))

[
  {
    "Title": "Das Extremum der Form\u00e4nderungsarbeit",
    "Authors": [
      "Georg Prange"
    ],
    "Year": "1916",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Terrorismus und Kommunismus",
    "Authors": [
      "Karl Kautsky"
    ],
    "Year": "1919",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "\u0098Das\u009c islamische Fremdenrecht bis zu den islamisch-fra\u0308nkischen Staatsvertra\u0308gen: Eine rechtshistor. Studie zum Fiqh",
    "Authors": [
      "Willi Heffening"
    ],
    "Year": "1921",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Kritik der Lehre Leonbards Erf\u00fcllungsort Schuldort m. Ber\u00fccks. fremder Rechte u. bes. des islamisch-t\u00fcrk. Rechts",
    "Authors": [
      "Mehmed F\u00e9rid"
    ],
    "Year": "1923",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Hygiene im Lichte des Islams",
    "Authors": [
      "Mohamed Abdul Chalik Dalgamoni"
    ],
    "Year": "1925",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Seven pillars of wisdom: A triumph",
    "Authors": [
      "T. E. Lawrence"
    ],
    "Year": "1926",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "Astronomical instruments and observatories in the islamic world",
    "Authors": [
      "Fritz Schmidt"
    ],
    "Year": "1929",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Fortschritte in der Behandlung der pernizi\u00f6sen An\u00e4mie",
    "Authors": [
      "Rasi Islami"
    ],
    "Year": "1930",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Zakonodavstvo o islamskoj verskoj zajednici Kraljevine Jugoslavije",
    "Authors": [
      "Gojko Niketi\u0107"
    ],
    "Year": "1932",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "\u00acLes Comitadjis ou le terrorisme dans les Balkans",
    "Authors": [
      "Albert Londres"
    ],
    "Year": "1932",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "M\u00f6nchsideale des Islams nach Ghazalis Abhandlung \u00fcber Armut und Weltentsagung",
    "Authors": [
      "Ernst Friedrich Tscheuschner"
    ],
    "Year": "1933",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Studies in Islamic atomism",
    "Authors": [
      "Shelomoh Pines"
    ],
    "Year": "1936",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Der weltliche dritte Orden als religionsgeschichtliche Erscheinung, aufgezeigt am Hinay na-Buddhismus, den Derwischorden des Islams und den Orden der katholischen Kirche",
    "Authors": [
      "Erich Kr\u00e4tzig"
    ],
    "Year": "1939",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Infektion und Prophylaxe im Islam: Stellg d. Islams zur heutigen med. Wissenschaft u. s. Einfluss auf d. Lebensweise s. Anh\u00e4nger",
    "Authors": [
      "Ahmed Kadri Hawasli"
    ],
    "Year": "1943",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Extremum problems with inequalities as subsidiary conditions",
    "Authors": [
      "Fritz John"
    ],
    "Year": "1948",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Die muslimischen Heere der Eroberungszeit: <Das Instrument d. Ausbreitg d. Islams, s. Aufbau, s. Gliederg, s. F\u00fchrg u. s. Einsatz.> 622-651",
    "Authors": [
      "Leo Hans Hermann Beckmann"
    ],
    "Year": "1953",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "The frequency distribution of the annual maximum (or minimum) values of meteorological elements",
    "Authors": [
      "A. F. Jenkinson"
    ],
    "Year": "1955",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Izlo\u017eba islamskih rukopisa u Beogradu",
    "Authors": [
      "Mehmed Mujezinovi\u0107"
    ],
    "Year": "1958",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Islamic Law: Its scope and equity",
    "Authors": [
      "Sa\u00ca\u00bf Rama n"
    ],
    "Year": "1959",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "The Lodi Phase of Indo-Islamic architecture: <1451 to 1526 A.D.>",
    "Authors": [
      "Muhammad Sir ju-'l-Isl m"
    ],
    "Year": "1961",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Les m\u00e9tiers vils en Islam",
    "Authors": [
      "Robert Brunschvig"
    ],
    "Year": "1962",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Paradise on Earth. Some thoughts on European Images of Non-European Man",
    "Authors": [
      "Henri Baudet"
    ],
    "Year": "1965",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Katalog arapskih, turskih i perzijskih rukopisa Gazi Husref-begove biblioteke u Sarajevu, izdanje Starje\u0161instva Islamske vjerske zajednice, Sarajevo 1963",
    "Authors": [
      "Mehmed Mujezinovi\u0107"
    ],
    "Year": "1965",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Iran's first Experience of Military Coup d'Etat in the Era of her Constitutional Government",
    "Authors": [
      "Mohammed Djawad Scheikh-ol-Islami"
    ],
    "Year": "1965",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Die Stellung des Negers in der islamisch-arabischen Gesellschaft bis zum 16. Jahrhundert",
    "Authors": [
      "Gernot Rotter"
    ],
    "Year": "1966",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Economic failure, alienation, and extremism",
    "Authors": [
      "Michael Aiken",
      "Louis A. Ferman",
      "Harold L. Sheppard"
    ],
    "Year": "1968",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "The Politics of Unreason. Right\"=Wing Extremism in America, 1790-1970",
    "Authors": [
      "Seymour Martin Lipset",
      "Earl Raab"
    ],
    "Year": "1971",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Upper extremity bracing of the severely athetoid mental retardate.",
    "Authors": [
      "J. Waylett",
      "L. Barber"
    ],
    "Year": "1971",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Experience with plastic lower extremity orthoses.",
    "Authors": [
      "J. T. Demopoulos",
      "A. Cassvan",
      "J. M. Snowden"
    ],
    "Year": "1972",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Numerical Algorithms for Global Extremum Search.",
    "Authors": [
      "J. Evtushenko"
    ],
    "Year": "1973",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Limit Extremum Problems.",
    "Authors": [
      "Yuri M. Ermoliev",
      "Evgeni A. Nurminski"
    ],
    "Year": "1974",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Upper extremity tendon transfers in cerebral palsy.",
    "Authors": [
      "J. L. Goldner"
    ],
    "Year": "1974",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "On Bayesian Methods for Seeking the Extremum.",
    "Authors": [
      "Jonas Mockus"
    ],
    "Year": "1974",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Follow-up study on upper extremity bracing of children with severe athetosis.",
    "Authors": [
      "P. Largent",
      "J. Waylett"
    ],
    "Year": "1975",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Surgery of the lower extremity in cerebral palsy: considerations and approaches.",
    "Authors": [
      "B. Pettitt"
    ],
    "Year": "1976",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "On the joint distribution of the largest flood and its time of occurrence",
    "Authors": [
      "Vijay K. Gupta",
      "L. Duckstein",
      "R. W. Peebles"
    ],
    "Year": "1976",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Christianization in the Fourth Century: The Example of Roman Women",
    "Authors": [
      "Anne Yarbrough"
    ],
    "Year": "1976",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Aspekte des internationalen Terrorismus als transnationales Problem: dargest. am Beispiel der terroristischen Geiselnahmen von 1968 bis 1977 ; Versuch e. Bestandsaufnahme",
    "Authors": [
      "Ulrike Pesch"
    ],
    "Year": "1977",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "Islamic Medicine",
    "Authors": [
      "Manfred Ullmann"
    ],
    "Year": "1978",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Dynamic electromyography and decision-making for surgery in the upper extremity of patients with cerebral palsy.",
    "Authors": [
      "M. M. Hoffer",
      "J. Perry",
      "G. J. Melkonian"
    ],
    "Year": "1979",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Die Beziehungen der P\u00e4pste zu islamischen und mongolischen Herrschern im 13. Jahrhundert anhand ihres Briefwechsels",
    "Authors": [
      "Karl-Ernst Lupprian"
    ],
    "Year": "1981",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Principle and application of orthotic therapy for lower extremity",
    "Authors": [
      "S. Kakurai"
    ],
    "Year": "1981",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Sozialpsychologie des Terrorismus",
    "Authors": [
      "Michael Horn"
    ],
    "Year": "1981",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "Pal\u00e4stinenser zwischen Terrorismus und Diplomatie: d. paramilit\u00e4r. pal\u00e4stinens. Nationalbewegung von 1918 bis 1981",
    "Authors": [
      "David Th Schiller"
    ],
    "Year": "1982",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "Extremes in autoregressive processes with uniform marginal distributions",
    "Authors": [
      "Michael R. Chernick",
      "Richard A. Davis"
    ],
    "Year": "1982",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Finding an extremum in a network.",
    "Authors": [
      "Steven P. Levitan",
      "Caxton C. Foster"
    ],
    "Year": "1982",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "International computer crime: Where terrorism and transborder data flow meet.",
    "Authors": [
      "Jay BloomBecker"
    ],
    "Year": "1982",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "On extremum-searching approximate probabilistic algorithms.",
    "Authors": [
      "Ivan Kramosil"
    ],
    "Year": "1983",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Opposites and Measures of Extremism in Concepts and Constructs.",
    "Authors": [
      "Ronald R. Yager"
    ],
    "Year": "1983",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Extremes and Related Properties of Random Sequences and Processes",
    "Authors": [
      "M. R. Leadbetter",
      "G. Lindgren",
      "H. Rootzen"
    ],
    "Year": "1983",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Implications of International Terrorism on Security of Information Systems.",
    "Authors": [
      "Raoul Pollak"
    ],
    "Year": "1983",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "Portfolio management of islamic banks : `Certainty model'",
    "Authors": [
      "B. A. Bashir"
    ],
    "Year": "1983",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "An Extremum Principle for Shape From Contour.",
    "Authors": [
      "Michael Brady",
      "Alan L. Yuille"
    ],
    "Year": "1983",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Zwischen Reform und Rebellion: u\u0308ber d. Entwicklung d. Islams in Minangkabau (Westsumatra) zwischen d. beiden Reformbewegungen d. Padri (1837) u.d. Modernisten (1908) ; e. Beitr. zur Geschichte d. Islamisierung Indonesiens",
    "Authors": [
      "Werner Kraus"
    ],
    "Year": "1984",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "An Extremum Principle for Shape from Contour.",
    "Authors": [
      "Michael Brady",
      "Alan L. Yuille"
    ],
    "Year": "1984",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Die Gesetzgebung zur Bek\u00e4mpfung des Terrorismus aus strafrechtlich-soziologischer Sicht",
    "Authors": [
      "Werner Klughardt"
    ],
    "Year": "1984",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "Sozialstrukturelle Bedingen des \"linken Terrorismus\u201c der 70er Jahre. Aufgrund eines Vergleichs der Entwicklun-\r\ngen in der Bundesrepublik Deutschland, in Italien,\r\nFrankreich und den Niederlanden",
    "Authors": [
      "Heinz Steinert",
      "Henner Hess",
      "Susanne Karstadt-Henke",
      "Martin Moerings",
      "Dieter Paas",
      "Sebastian Scheerer"
    ],
    "Year": "1984",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "Zwischen Reform und Rebellion: \u00fcber d. Entwicklung d. Islams in Minangkabau (Westsumatra) zwischen d. beiden Reformbewegungen d. Padri (1837) u.d. Modernisten (1908) ; e. Beitr. zur Geschichte d. Islamisierung Indonesiens",
    "Authors": [
      "Werner Kraus"
    ],
    "Year": "1984",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Threshold Methods for Sample Extremes",
    "Authors": [
      "Richard L. Smith"
    ],
    "Year": "1984",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Nach dem Terroranschlag auf eine Schulklasse",
    "Authors": [
      "Ingrid Fl\u00fcgge"
    ],
    "Year": "1985",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "Management of the upper extremity in cerebral palsy.",
    "Authors": [
      "H. Skoff",
      "D. F. Woodbury"
    ],
    "Year": "1985",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Der Islam im Spiegel westlicher Theologie: Aspekte christl.-theol. Beurteilung d. Islams im 20. Jh.",
    "Authors": [
      "Klaus Hock"
    ],
    "Year": "1985",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Terrorismus und Politikwissenschaft in der Bundesrepublik Deutschland",
    "Authors": [
      "Gerhard Hertel"
    ],
    "Year": "1985",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "One-session surgery for correction of lower extremity deformities in children with cerebral palsy.",
    "Authors": [
      "R. Norlin",
      "H. Tkaczuk"
    ],
    "Year": "1985",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Extreme value theory based on the r largest annual events",
    "Authors": [
      "Richard L. Smith"
    ],
    "Year": "1986",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Penultimate versus ultimate in statistical theory of extremes a simulation study",
    "Authors": [
      "M. Ivette Gomes"
    ],
    "Year": "1986",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Das staatliche Familienplanungsprogramm Tunesiens: Vorgeschichte, Entwicklung, Hintergr\u00fcnde ; unter Ber\u00fccks. d. Volksmedizin, traditioneller Lebensformen u. d. Islams ; d. Innenpolitik, d. Wirtschaftspolitik u. d. beschleunigten sozialen Wertewandels sowie internat. Einfl\u00fcsse",
    "Authors": [
      "Wolfgang Streit"
    ],
    "Year": "1986",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Doors and thresholds: Jeddi's approach to psychiatric disorders",
    "Authors": [
      "Renaat Devisch",
      "Bart Vervaeck"
    ],
    "Year": "1986",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Extreme Values of Non-Stationary Random Sequences",
    "Authors": [
      "J\u00fcrg H\u00fcsler"
    ],
    "Year": "1986",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Extremes Abschrecken supraleitender Materialien aus dem festen Zustand",
    "Authors": [
      "Wolfgang Krauss"
    ],
    "Year": "1986",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "From silver to ceramic : the Potter's debt to metalwork in the Graeco-Roman, Oriental and Islamic worlds",
    "Authors": [
      "Michael Vickers",
      "Oliver Impey",
      "James W. Allan"
    ],
    "Year": "1986",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Islamic banking",
    "Authors": [
      "Sami H. Homoud"
    ],
    "Year": "1986",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Seating orientations and upper extremity function in children with cerebral palsy.",
    "Authors": [
      "O. M. Nwaobi"
    ],
    "Year": "1987",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Men of modest substance",
    "Authors": [
      "Suraiya Faroqhi"
    ],
    "Year": "1987",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Assessment and management of the lower extremity in cerebral palsy.",
    "Authors": [
      "E. T. Jones",
      "D. R. Knapp"
    ],
    "Year": "1987",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Der Gegensatz islamisch-westlich im Menschenbild zeitgen\u00f6ssischer schiitischer Beitr\u00e4ge im Iran, unter besonderer Ber\u00fccksichtigung von Motahhari und Schariati",
    "Authors": [
      "Abdol Reza Navah"
    ],
    "Year": "1987",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "The Origins of the Islamic Hospital: Myth and Reality",
    "Authors": [
      "Michael W. Dols"
    ],
    "Year": "1987",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {
    "Title": "Political terrorism: A new guide to actors, authors, concepts, data bases, theories, and literature",
    "Authors": [
      "Alex Peter Schmid",
      "A. J. Jongman",
      "Michael Stohl"
    ],
    "Year": "1988",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "Investigations of upper extremity visuomotor control performance measures.",
    "Authors": [
      "Khosrow Behbehani",
      "George V. Kondraske",
      "J. Robin Richmond"
    ],
    "Year": "1988",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "The world meganetwork and terrorism.",
    "Authors": [
      "C. Wayne Madsen"
    ],
    "Year": "1988",
    "Type": "Publication",
    "Search Term": "Terrorismus"
  },
  {
    "Title": "Extremum-searching hierarchical parallel probabilistic algorithms.",
    "Authors": [
      "Ivan Kramosil"
    ],
    "Year": "1988",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "An extreme-value theory model for dependent observations",
    "Authors": [
      "Jonathan A. Tawn"
    ],
    "Year": "1988",
    "Type": "Publication",
    "Search Term": "Extremism"
  },
  {
    "Title": "Christian Life in Palestine during the Early Islamic Period",
    "Authors": [
      "Robert Schick"
    ],
    "Year": "1988",
    "Type": "Publication",
    "Search Term": "Islamism"
  },
  {