In [1]:
import pandas as pd
import numpy as np
import pyterrier as pt
import pickle

In [3]:
df_bibsonomy = pd.read_json('bibsonomy.json')
df_bibsonomy

,id,tags,query,title,description,date,url,year,author,authors,text,pages,abstract
1000,https://www.bibsonomy.org/bibtex/24e338b04bc2a...,[710-714],artificial intelligence,Artificial Intelligence in Agriculture,,2021-04-13 13:15:04,https://www.ijtsrd.com/engineering/electrical-...,2021,"[Matthew N. O. Sadiku, Sarhan M. Musa, Abayomi...",[{'first': 'Matthew N. O. Sadiku | Sarhan M. M...,None,710-714,Artificial Intelligence is one of the emerging...
1001,https://www.bibsonomy.org/bibtex/29f3b59303571...,"[Artificial, Intelligence, Risks, and, Benefits]",artificial intelligence,Artificial Intelligence Benefit and Risks,,2020-05-14 10:40:49,https://www.ijtsrd.com/computer-science/artifi...,2020,[Seeta M. Chauhan],"[{'first': 'Seeta M.', 'last': 'Chauhan'}]",None,1007-1009,this article demonstrate Disadvantage of artif...
1002,https://www.bibsonomy.org/bibtex/24bc08fb79365...,"[ANN, Fuzzylogic, ElectricalEngineering, Artif...",artificial intelligence,Artificial Intelligence in Power Station,,2020-01-10 09:23:37,https://www.ijtsrd.com/engineering/electrical-...,2019,"[P. Naveen, S. Nikitha, P. Sudeesh, V. Vaishnavi]",[{'first': 'P. Naveen | S. Nikitha | P. Sudees...,None,1020-1025,With increased competitiveness in power genera...
1003,https://www.bibsonomy.org/bibtex/29f87881e4dec...,"[Artificial, Intelligence, Markup, Chatbot, La...",artificial intelligence,Artificial Intelligence Based Training and Pla...,,2019-03-26 12:35:44,http://www.ijtsrd.com/computer-science/artific...,2018,"[Krishanu Deb, Pankaj Agrawal, Harish Nawale, ...",[{'first': 'Krishanu Deb | Pankaj Agrawal | Ha...,None,1057-1060,Training and placement cell in colleges is to ...
1004,https://www.bibsonomy.org/bibtex/263320f0ab96a...,"[Learning,, Systems,, Artificialintelligence, ...",artificial intelligence,The Significance of Artificial Intelligence in...,,2023-10-14 13:59:49,https://www.ijtsrd.com/computer-science/artifi...,2023,[Dr. Atul Kumar Mishra],"[{'first': 'Dr. Atul Kumar', 'last': 'Mishra'}]",None,786-788,"In an increasingly digitalized world, the util..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7271,https://www.bibsonomy.org/bibtex/2521eb5477437...,[LSAP],language model,A Decomposable Attention Model for Natural Lan...,,2019-02-19 13:56:10,http://dblp.uni-trier.de/db/journals/corr/corr...,2016,"[Ankur P. Parikh, Oscar Täckström, Dipanjan Da...","[{'first': 'Ankur P.', 'last': 'Parikh'}, {'fi...",None,None,None
7272,https://www.bibsonomy.org/bibtex/2521eb5477437...,[deepMatching],language model,A Decomposable Attention Model for Natural Lan...,,2018-08-02 21:36:31,http://dblp.uni-trier.de/db/journals/corr/corr...,2016,"[Ankur P. Parikh, Oscar Täckström, Dipanjan Da...","[{'first': 'Ankur P.', 'last': 'Parikh'}, {'fi...",None,None,None
7273,https://www.bibsonomy.org/bibtex/26b29953c87a0...,[dblp],language model,An Efficient Language Model Using Double-Array...,,2019-09-11 00:00:00,http://dblp.uni-trier.de/db/conf/emnlp/emnlp20...,2013,"[Makoto Yasuhara, Toru Tanaka, Jun ya Norimats...","[{'first': 'Makoto', 'last': 'Yasuhara'}, {'fi...",None,222-232,None
7274,https://www.bibsonomy.org/bibtex/2b1b8a871f03e...,[dblp],language model,Style & Topic Language Model Adaptation Using ...,,2019-09-13 00:00:00,http://dblp.uni-trier.de/db/conf/emnlp/emnlp20...,2006,"[Bo-June Paul Hsu, James R. Glass]","[{'first': 'Bo-June Paul', 'last': 'Hsu'}, {'f...",None,373-381,None
7275,https://www.bibsonomy.org/bibtex/2fc318678d505...,[dblp],language model,Towards Model Driven Architectures for Human L...,,2018-05-25 00:00:00,http://dblp.uni-trier.de/db/conf/coling/oiaf4h...,2014,"[Alessandro Di Bari, Guido Vetere, Kateryna Ty...","[{'first': 'Alessandro Di', 'last': 'Bari'}, {...",None,23-33,None

In [4]:
df_bibsonomy["source"] = "Bibsonomy"
df_bibsonomy

,id,tags,query,title,description,date,url,year,author,authors,text,pages,abstract,source
1000,https://www.bibsonomy.org/bibtex/24e338b04bc2a...,[710-714],artificial intelligence,Artificial Intelligence in Agriculture,,2021-04-13 13:15:04,https://www.ijtsrd.com/engineering/electrical-...,2021,"[Matthew N. O. Sadiku, Sarhan M. Musa, Abayomi...",[{'first': 'Matthew N. O. Sadiku | Sarhan M. M...,None,710-714,Artificial Intelligence is one of the emerging...,Bibsonomy
1001,https://www.bibsonomy.org/bibtex/29f3b59303571...,"[Artificial, Intelligence, Risks, and, Benefits]",artificial intelligence,Artificial Intelligence Benefit and Risks,,2020-05-14 10:40:49,https://www.ijtsrd.com/computer-science/artifi...,2020,[Seeta M. Chauhan],"[{'first': 'Seeta M.', 'last': 'Chauhan'}]",None,1007-1009,this article demonstrate Disadvantage of artif...,Bibsonomy
1002,https://www.bibsonomy.org/bibtex/24bc08fb79365...,"[ANN, Fuzzylogic, ElectricalEngineering, Artif...",artificial intelligence,Artificial Intelligence in Power Station,,2020-01-10 09:23:37,https://www.ijtsrd.com/engineering/electrical-...,2019,"[P. Naveen, S. Nikitha, P. Sudeesh, V. Vaishnavi]",[{'first': 'P. Naveen | S. Nikitha | P. Sudees...,None,1020-1025,With increased competitiveness in power genera...,Bibsonomy
1003,https://www.bibsonomy.org/bibtex/29f87881e4dec...,"[Artificial, Intelligence, Markup, Chatbot, La...",artificial intelligence,Artificial Intelligence Based Training and Pla...,,2019-03-26 12:35:44,http://www.ijtsrd.com/computer-science/artific...,2018,"[Krishanu Deb, Pankaj Agrawal, Harish Nawale, ...",[{'first': 'Krishanu Deb | Pankaj Agrawal | Ha...,None,1057-1060,Training and placement cell in colleges is to ...,Bibsonomy
1004,https://www.bibsonomy.org/bibtex/263320f0ab96a...,"[Learning,, Systems,, Artificialintelligence, ...",artificial intelligence,The Significance of Artificial Intelligence in...,,2023-10-14 13:59:49,https://www.ijtsrd.com/computer-science/artifi...,2023,[Dr. Atul Kumar Mishra],"[{'first': 'Dr. Atul Kumar', 'last': 'Mishra'}]",None,786-788,"In an increasingly digitalized world, the util...",Bibsonomy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7271,https://www.bibsonomy.org/bibtex/2521eb5477437...,[LSAP],language model,A Decomposable Attention Model for Natural Lan...,,2019-02-19 13:56:10,http://dblp.uni-trier.de/db/journals/corr/corr...,2016,"[Ankur P. Parikh, Oscar Täckström, Dipanjan Da...","[{'first': 'Ankur P.', 'last': 'Parikh'}, {'fi...",None,None,None,Bibsonomy
7272,https://www.bibsonomy.org/bibtex/2521eb5477437...,[deepMatching],language model,A Decomposable Attention Model for Natural Lan...,,2018-08-02 21:36:31,http://dblp.uni-trier.de/db/journals/corr/corr...,2016,"[Ankur P. Parikh, Oscar Täckström, Dipanjan Da...","[{'first': 'Ankur P.', 'last': 'Parikh'}, {'fi...",None,None,None,Bibsonomy
7273,https://www.bibsonomy.org/bibtex/26b29953c87a0...,[dblp],language model,An Efficient Language Model Using Double-Array...,,2019-09-11 00:00:00,http://dblp.uni-trier.de/db/conf/emnlp/emnlp20...,2013,"[Makoto Yasuhara, Toru Tanaka, Jun ya Norimats...","[{'first': 'Makoto', 'last': 'Yasuhara'}, {'fi...",None,222-232,None,Bibsonomy
7274,https://www.bibsonomy.org/bibtex/2b1b8a871f03e...,[dblp],language model,Style & Topic Language Model Adaptation Using ...,,2019-09-13 00:00:00,http://dblp.uni-trier.de/db/conf/emnlp/emnlp20...,2006,"[Bo-June Paul Hsu, James R. Glass]","[{'first': 'Bo-June Paul', 'last': 'Hsu'}, {'f...",None,373-381,None,Bibsonomy
7275,https://www.bibsonomy.org/bibtex/2fc318678d505...,[dblp],language model,Towards Model Driven Architectures for Human L...,,2018-05-25 00:00:00,http://dblp.uni-trier.de/db/conf/coling/oiaf4h...,2014,"[Alessandro Di Bari, Guido Vetere, Kateryna Ty...","[{'first': 'Alessandro Di', 'last': 'Bari'}, {...",None,23-33,None,Bibsonomy

In [5]:
df_scholar = pd.read_json('semantic_scholar.json')
df_scholar

,index,paperId,externalIds,publicationVenue,url,title,abstract,venue,year,referenceCount,...,influentialCitationCount,isOpenAccess,openAccessPdf,fieldsOfStudy,publicationTypes,publicationDate,journal,citationStyles,authors,searchQuery
0,0,574beee702be3856d60aa482ec725168fe64fc99,"{'ArXiv': '2303.12712', 'DBLP': 'journals/corr...","{'id': '1901e811-ee72-4b20-8f7e-de08cd395a10',...",https://www.semanticscholar.org/paper/574beee7...,Sparks of Artificial General Intelligence: Ear...,Artificial intelligence (AI) researchers have ...,arXiv.org,2023,0,...,114,True,"{'url': 'http://arxiv.org/pdf/2303.12712', 'st...",[Computer Science],[JournalArticle],2023-03-22,"{'name': 'ArXiv', 'volume': 'abs/2303.12712'}","{'bibtex': '@Article{Bubeck2023SparksOA, auth...","[{'authorId': '121645690', 'name': 'Sébastien ...",artificial intelligence
1,1,e1d2f2a717aa03280126f87c8e5fad695f52bf7c,"{'DOI': '10.48047/ijfans/v12/i1/271', 'CorpusI...","{'id': '50c199ea-1ec5-4c24-a902-d9ce8d810efa',...",https://www.semanticscholar.org/paper/e1d2f2a7...,Explainable Artificial Intelligence (XAI),Explainable Artificial Intelligence (XAI) has ...,International Journal of Food and Nutritional ...,2023,33,...,44,True,{'url': 'https://www.ijfans.org/uploads/paper/...,None,[JournalArticle],2023-10-26,{'name': 'international journal of food and nu...,"{'bibtex': '@Article{Sewada2023ExplainableAI, ...","[{'authorId': '2151645335', 'name': 'Ranu Sewa...",artificial intelligence
2,2,530a059cb48477ad1e3d4f8f4b153274c8997332,"{'ArXiv': '1910.10045', 'DBLP': 'journals/inff...","{'id': '06afdd0b-0d85-413f-af8a-c3045c12c561',...",https://www.semanticscholar.org/paper/530a059c...,Explainable Artificial Intelligence (XAI): Con...,None,Information Fusion,2019,430,...,256,True,{'url': 'https://bird.bcamath.org/bitstream/20...,[Computer Science],"[JournalArticle, Review]",2019-10-22,"{'name': 'Inf. Fusion', 'pages': '82-115', 'vo...","{'bibtex': '@Article{Arrieta2019ExplainableAI,...","[{'authorId': '1379511816', 'name': 'Alejandro...",artificial intelligence
3,3,de4b9bc12ddb6b9f6090c032ef5c6290bd64ef36,"{'DBLP': 'conf/bnaic/2017', 'MAG': '2895834617...","{'id': '82cd90f0-386f-4446-b237-6404c27f6a15',...",https://www.semanticscholar.org/paper/de4b9bc1...,Artificial Intelligence,None,Communications in Computer and Information Sci...,2017,27,...,250,True,None,[Computer Science],[Review],None,{'volume': '823'},{'bibtex': '@Inproceedings{Verheij2017Artifici...,"[{'authorId': '1697177', 'name': 'Bart Verheij...",artificial intelligence
4,4,f134abeaf9bfd41f29b97aec675ec31895bf541d,"{'MAG': '2908201961', 'DOI': '10.1038/s41591-0...","{'id': '9e995b6d-f30b-4ab4-a13b-3dc2cc992f47',...",https://www.semanticscholar.org/paper/f134abea...,High-performance medicine: the convergence of ...,None,Nature Network Boston,2019,227,...,77,False,None,"[Computer Science, Medicine]","[Review, JournalArticle]",2019-01-01,"{'name': 'Nature Medicine', 'pages': '44 - 56'...",{'bibtex': '@Article{Topol2019HighperformanceM...,"[{'authorId': '144758045', 'name': 'E. Topol'}]",artificial intelligence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,1495,f1a8ff5542ffd51c3618953e5cf926c467154f79,"{'DBLP': 'conf/emnlp/BharadwajMDC16', 'ACL': '...","{'id': '41bf9ed3-85b3-4c90-b015-150e31690253',...",https://www.semanticscholar.org/paper/f1a8ff55...,Phonologically Aware Neural Model for Named En...,Named Entity Recognition is a well established...,Conference on Empirical Methods in Natural Lan...,2016,39,...,4,True,{'url': 'https://www.aclweb.org/anthology/D16-...,[Computer Science],"[JournalArticle, Conference]",2016-11-01,{'pages': '1462-1472'},{'bibtex': '@Article{Bharadwaj2016Phonological...,"[{'authorId': '2528900', 'name': 'Akash Bharad...",large language model
4496,1496,591080c335daba2494f18cc04c9f7071501af0eb,"{'MAG': '2017708149', 'DBLP': 'conf/icassp/Ema...","{'id': '0d6f7fba-7092-46b3-8039-93458dba736b',...",https://www.semanticscholar.org/paper/591080c3...,Large-Scale Distributed Language Modeling,A novel distributed language model that has no...,"IEEE International Conference on Acoustics, Sp...",2007,12,...,1,False,None,[Computer Science],"[JournalArticle, Conference]",2007-04-15,{'name': '2007 IEEE International Conference o...,"{'bibtex': '@Article{Emami2007LargeScaleDL, a...","[{'authorId': '35797272', 'name': 'Ahmad Emami...",large language model
4497,1497,476029ac9be26bf7f121a388f5c1e45d204efe52,"{'MAG': '2917128112', 'DBLP': 'journals/corr/a...","{'id': '1901e811-ee72-4b20-8f7e-de08cd395a10',...",https://www.semanticscholar.org/paper/476029ac...,BERT for Joint Intent Classification and Slot ...,Intent classification and slot filling are two...,arXiv.org,2019,26,...,81,False,None,[Computer Science],[JournalArticle],2019-02-28,"{'name': 'ArXiv', 'volume': 'abs/1902.10909'}","{'bibtex': '@Article{Chen2019BERTFJ, author =...","[{'authorId': '47261124', 'name': 'Qian Chen'}...",large language model
4498,1498,b281a9d0c728979f7ffccba1a61d0fc1d29530c1,"{'ACL': 'D08-1090', 'MAG': '2116042738', 'DBLP...","{'id': '41bf9ed3-85b3-4c90-b015-150e31690253',...",https://www.semanticscholar.org/paper/b281a9d0...,Language and Translation Model Adaptation usin...,"Traditionally, statistical machine translation...",Conference on Empirical Methods in Natural Lan...,2008,21,...,5,True,{'url': 'http://dl.acm.org/ft_gateway.cfm?id=1...,[Computer Science],"[JournalArticle, Conference]",2008-10-25,{'pages': '857-866'},"{'bibtex': '@Article{Snover2008LanguageAT, au...","[{'authorId': '32278254', 'name': 'M. Snover'}...",large language model
4499,1499,f98e135986414cccf29aec593d547c0656e4d82c,"{'DBLP': 'conf/emnlp/DavisonFR19', 'MAG': '297...","{'id': '41bf9ed3-85b3-4c90-b015-150e31690253',...",https://www.semanticscholar.org/paper/f98e1359...,Commonsense Knowledge Mining from Pretrained M...,Inferring commonsense knowledge is a key chall...,Conference on Empirical Methods in Natural Lan...,2019,19,...,21,True,{'url': 'https://www.aclweb.org/anthology/D19-...,[Computer Science],"[JournalArticle, Conference]",2019-09-01,"{'name': 'ArXiv', 'volume': 'abs/1909.00505'}","{'bibtex': '@Article{Feldman2019CommonsenseKM,...","[{'authorId': '2072080518', 'name': 'Joshua Fe...",large language model

In [6]:
df_scholar["source"] = "Semantic Scholar"
df_scholar

,index,paperId,externalIds,publicationVenue,url,title,abstract,venue,year,referenceCount,...,isOpenAccess,openAccessPdf,fieldsOfStudy,publicationTypes,publicationDate,journal,citationStyles,authors,searchQuery,source
0,0,574beee702be3856d60aa482ec725168fe64fc99,"{'ArXiv': '2303.12712', 'DBLP': 'journals/corr...","{'id': '1901e811-ee72-4b20-8f7e-de08cd395a10',...",https://www.semanticscholar.org/paper/574beee7...,Sparks of Artificial General Intelligence: Ear...,Artificial intelligence (AI) researchers have ...,arXiv.org,2023,0,...,True,"{'url': 'http://arxiv.org/pdf/2303.12712', 'st...",[Computer Science],[JournalArticle],2023-03-22,"{'name': 'ArXiv', 'volume': 'abs/2303.12712'}","{'bibtex': '@Article{Bubeck2023SparksOA, auth...","[{'authorId': '121645690', 'name': 'Sébastien ...",artificial intelligence,Semantic Scholar
1,1,e1d2f2a717aa03280126f87c8e5fad695f52bf7c,"{'DOI': '10.48047/ijfans/v12/i1/271', 'CorpusI...","{'id': '50c199ea-1ec5-4c24-a902-d9ce8d810efa',...",https://www.semanticscholar.org/paper/e1d2f2a7...,Explainable Artificial Intelligence (XAI),Explainable Artificial Intelligence (XAI) has ...,International Journal of Food and Nutritional ...,2023,33,...,True,{'url': 'https://www.ijfans.org/uploads/paper/...,None,[JournalArticle],2023-10-26,{'name': 'international journal of food and nu...,"{'bibtex': '@Article{Sewada2023ExplainableAI, ...","[{'authorId': '2151645335', 'name': 'Ranu Sewa...",artificial intelligence,Semantic Scholar
2,2,530a059cb48477ad1e3d4f8f4b153274c8997332,"{'ArXiv': '1910.10045', 'DBLP': 'journals/inff...","{'id': '06afdd0b-0d85-413f-af8a-c3045c12c561',...",https://www.semanticscholar.org/paper/530a059c...,Explainable Artificial Intelligence (XAI): Con...,None,Information Fusion,2019,430,...,True,{'url': 'https://bird.bcamath.org/bitstream/20...,[Computer Science],"[JournalArticle, Review]",2019-10-22,"{'name': 'Inf. Fusion', 'pages': '82-115', 'vo...","{'bibtex': '@Article{Arrieta2019ExplainableAI,...","[{'authorId': '1379511816', 'name': 'Alejandro...",artificial intelligence,Semantic Scholar
3,3,de4b9bc12ddb6b9f6090c032ef5c6290bd64ef36,"{'DBLP': 'conf/bnaic/2017', 'MAG': '2895834617...","{'id': '82cd90f0-386f-4446-b237-6404c27f6a15',...",https://www.semanticscholar.org/paper/de4b9bc1...,Artificial Intelligence,None,Communications in Computer and Information Sci...,2017,27,...,True,None,[Computer Science],[Review],None,{'volume': '823'},{'bibtex': '@Inproceedings{Verheij2017Artifici...,"[{'authorId': '1697177', 'name': 'Bart Verheij...",artificial intelligence,Semantic Scholar
4,4,f134abeaf9bfd41f29b97aec675ec31895bf541d,"{'MAG': '2908201961', 'DOI': '10.1038/s41591-0...","{'id': '9e995b6d-f30b-4ab4-a13b-3dc2cc992f47',...",https://www.semanticscholar.org/paper/f134abea...,High-performance medicine: the convergence of ...,None,Nature Network Boston,2019,227,...,False,None,"[Computer Science, Medicine]","[Review, JournalArticle]",2019-01-01,"{'name': 'Nature Medicine', 'pages': '44 - 56'...",{'bibtex': '@Article{Topol2019HighperformanceM...,"[{'authorId': '144758045', 'name': 'E. Topol'}]",artificial intelligence,Semantic Scholar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,1495,f1a8ff5542ffd51c3618953e5cf926c467154f79,"{'DBLP': 'conf/emnlp/BharadwajMDC16', 'ACL': '...","{'id': '41bf9ed3-85b3-4c90-b015-150e31690253',...",https://www.semanticscholar.org/paper/f1a8ff55...,Phonologically Aware Neural Model for Named En...,Named Entity Recognition is a well established...,Conference on Empirical Methods in Natural Lan...,2016,39,...,True,{'url': 'https://www.aclweb.org/anthology/D16-...,[Computer Science],"[JournalArticle, Conference]",2016-11-01,{'pages': '1462-1472'},{'bibtex': '@Article{Bharadwaj2016Phonological...,"[{'authorId': '2528900', 'name': 'Akash Bharad...",large language model,Semantic Scholar
4496,1496,591080c335daba2494f18cc04c9f7071501af0eb,"{'MAG': '2017708149', 'DBLP': 'conf/icassp/Ema...","{'id': '0d6f7fba-7092-46b3-8039-93458dba736b',...",https://www.semanticscholar.org/paper/591080c3...,Large-Scale Distributed Language Modeling,A novel distributed language model that has no...,"IEEE International Conference on Acoustics, Sp...",2007,12,...,False,None,[Computer Science],"[JournalArticle, Conference]",2007-04-15,{'name': '2007 IEEE International Conference o...,"{'bibtex': '@Article{Emami2007LargeScaleDL, a...","[{'authorId': '35797272', 'name': 'Ahmad Emami...",large language model,Semantic Scholar
4497,1497,476029ac9be26bf7f121a388f5c1e45d204efe52,"{'MAG': '2917128112', 'DBLP': 'journals/corr/a...","{'id': '1901e811-ee72-4b20-8f7e-de08cd395a10',...",https://www.semanticscholar.org/paper/476029ac...,BERT for Joint Intent Classification and Slot ...,Intent classification and slot filling are two...,arXiv.org,2019,26,...,False,None,[Computer Science],[JournalArticle],2019-02-28,"{'name': 'ArXiv', 'volume': 'abs/1902.10909'}","{'bibtex': '@Article{Chen2019BERTFJ, author =...","[{'authorId': '47261124', 'name': 'Qian Chen'}...",large language model,Semantic Scholar
4498,1498,b281a9d0c728979f7ffccba1a61d0fc1d29530c1,"{'ACL': 'D08-1090', 'MAG': '2116042738', 'DBLP...","{'id': '41bf9ed3-85b3-4c90-b015-150e31690253',...",https://www.semanticscholar.org/paper/b281a9d0...,Language and Translation Model Adaptation usin...,"Traditionally, statistical machine translation...",Conference on Empirical Methods in Natural Lan...,2008,21,...,True,{'url': 'http://dl.acm.org/ft_gateway.cfm?id=1...,[Computer Science],"[JournalArticle, Conference]",2008-10-25,{'pages': '857-866'},"{'bibtex': '@Article{Snover2008LanguageAT, au...","[{'authorId': '32278254', 'name': 'M. Snover'}...",large language model,Semantic Scholar
4499,1499,f98e135986414cccf29aec593d547c0656e4d82c,"{'DBLP': 'conf/emnlp/DavisonFR19', 'MAG': '297...","{'id': '41bf9ed3-85b3-4c90-b015-150e31690253',...",https://www.semanticscholar.org/paper/f98e1359...,Commonsense Knowledge Mining from Pretrained M...,Inferring commonsense knowledge is a key chall...,Conference on Empirical Methods in Natural Lan...,2019,19,...,True,{'url': 'https://www.aclweb.org/anthology/D19-...,[Computer Science],"[JournalArticle, Conference]",2019-09-01,"{'name': 'ArXiv', 'volume': 'abs/1909.00505'}","{'bibtex': '@Article{Feldman2019CommonsenseKM,...","[{'authorId': '2072080518', 'name': 'Joshua Fe...",large language model,Semantic Scholar

In [7]:
df_merge = pd.concat([df_bibsonomy, df_scholar])

In [8]:
df_merge

,id,tags,query,title,description,date,url,year,author,authors,...,citationCount,influentialCitationCount,isOpenAccess,openAccessPdf,fieldsOfStudy,publicationTypes,publicationDate,journal,citationStyles,searchQuery
1000,https://www.bibsonomy.org/bibtex/24e338b04bc2a...,[710-714],artificial intelligence,Artificial Intelligence in Agriculture,,2021-04-13 13:15:04,https://www.ijtsrd.com/engineering/electrical-...,2021,"[Matthew N. O. Sadiku, Sarhan M. Musa, Abayomi...",[{'first': 'Matthew N. O. Sadiku | Sarhan M. M...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,https://www.bibsonomy.org/bibtex/29f3b59303571...,"[Artificial, Intelligence, Risks, and, Benefits]",artificial intelligence,Artificial Intelligence Benefit and Risks,,2020-05-14 10:40:49,https://www.ijtsrd.com/computer-science/artifi...,2020,[Seeta M. Chauhan],"[{'first': 'Seeta M.', 'last': 'Chauhan'}]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1002,https://www.bibsonomy.org/bibtex/24bc08fb79365...,"[ANN, Fuzzylogic, ElectricalEngineering, Artif...",artificial intelligence,Artificial Intelligence in Power Station,,2020-01-10 09:23:37,https://www.ijtsrd.com/engineering/electrical-...,2019,"[P. Naveen, S. Nikitha, P. Sudeesh, V. Vaishnavi]",[{'first': 'P. Naveen | S. Nikitha | P. Sudees...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003,https://www.bibsonomy.org/bibtex/29f87881e4dec...,"[Artificial, Intelligence, Markup, Chatbot, La...",artificial intelligence,Artificial Intelligence Based Training and Pla...,,2019-03-26 12:35:44,http://www.ijtsrd.com/computer-science/artific...,2018,"[Krishanu Deb, Pankaj Agrawal, Harish Nawale, ...",[{'first': 'Krishanu Deb | Pankaj Agrawal | Ha...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004,https://www.bibsonomy.org/bibtex/263320f0ab96a...,"[Learning,, Systems,, Artificialintelligence, ...",artificial intelligence,The Significance of Artificial Intelligence in...,,2023-10-14 13:59:49,https://www.ijtsrd.com/computer-science/artifi...,2023,[Dr. Atul Kumar Mishra],"[{'first': 'Dr. Atul Kumar', 'last': 'Mishra'}]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,NaN,NaN,NaN,Phonologically Aware Neural Model for Named En...,NaN,NaT,https://www.semanticscholar.org/paper/f1a8ff55...,2016,NaN,"[{'authorId': '2528900', 'name': 'Akash Bharad...",...,81.0,4.0,True,{'url': 'https://www.aclweb.org/anthology/D16-...,[Computer Science],"[JournalArticle, Conference]",2016-11-01,{'pages': '1462-1472'},{'bibtex': '@Article{Bharadwaj2016Phonological...,large language model
4496,NaN,NaN,NaN,Large-Scale Distributed Language Modeling,NaN,NaT,https://www.semanticscholar.org/paper/591080c3...,2007,NaN,"[{'authorId': '35797272', 'name': 'Ahmad Emami...",...,35.0,1.0,False,None,[Computer Science],"[JournalArticle, Conference]",2007-04-15,{'name': '2007 IEEE International Conference o...,"{'bibtex': '@Article{Emami2007LargeScaleDL, a...",large language model
4497,NaN,NaN,NaN,BERT for Joint Intent Classification and Slot ...,NaN,NaT,https://www.semanticscholar.org/paper/476029ac...,2019,NaN,"[{'authorId': '47261124', 'name': 'Qian Chen'}...",...,444.0,81.0,False,None,[Computer Science],[JournalArticle],2019-02-28,"{'name': 'ArXiv', 'volume': 'abs/1902.10909'}","{'bibtex': '@Article{Chen2019BERTFJ, author =...",large language model
4498,NaN,NaN,NaN,Language and Translation Model Adaptation usin...,NaN,NaT,https://www.semanticscholar.org/paper/b281a9d0...,2008,NaN,"[{'authorId': '32278254', 'name': 'M. Snover'}...",...,79.0,5.0,True,{'url': 'http://dl.acm.org/ft_gateway.cfm?id=1...,[Computer Science],"[JournalArticle, Conference]",2008-10-25,{'pages': '857-866'},"{'bibtex': '@Article{Snover2008LanguageAT, au...",large language model
4499,NaN,NaN,NaN,Commonsense Knowledge Mining from Pretrained M...,NaN,NaT,https://www.semanticscholar.org/paper/f98e1359...,2019,NaN,"[{'authorId': '2072080518', 'name': 'Joshua Fe...",...,285.0,21.0,True,{'url': 'https://www.aclweb.org/anthology/D19-...,[Computer Science],"[JournalArticle, Conference]",2019-09-01,"{'name': 'ArXiv', 'volume': 'abs/1909.00505'}","{'bibtex': '@Article{Feldman2019CommonsenseKM,...",large language model

In [9]:
df_merge.columns

Index(['id', 'tags', 'query', 'title', 'description', 'date', 'url', 'year',
       'author', 'authors', 'text', 'pages', 'abstract', 'source', 'index',
       'paperId', 'externalIds', 'publicationVenue', 'venue', 'referenceCount',
       'citationCount', 'influentialCitationCount', 'isOpenAccess',
       'openAccessPdf', 'fieldsOfStudy', 'publicationTypes', 'publicationDate',
       'journal', 'citationStyles', 'searchQuery'],
      dtype='object')

In [10]:
df_merge = df_merge[['title', 'authors', 'url', 'abstract', 'tags', 'query', 'source', 'year']]
df_merge

,title,authors,url,abstract,tags,query,source,year
1000,Artificial Intelligence in Agriculture,[{'first': 'Matthew N. O. Sadiku | Sarhan M. M...,https://www.ijtsrd.com/engineering/electrical-...,Artificial Intelligence is one of the emerging...,[710-714],artificial intelligence,Bibsonomy,2021
1001,Artificial Intelligence Benefit and Risks,"[{'first': 'Seeta M.', 'last': 'Chauhan'}]",https://www.ijtsrd.com/computer-science/artifi...,this article demonstrate Disadvantage of artif...,"[Artificial, Intelligence, Risks, and, Benefits]",artificial intelligence,Bibsonomy,2020
1002,Artificial Intelligence in Power Station,[{'first': 'P. Naveen | S. Nikitha | P. Sudees...,https://www.ijtsrd.com/engineering/electrical-...,With increased competitiveness in power genera...,"[ANN, Fuzzylogic, ElectricalEngineering, Artif...",artificial intelligence,Bibsonomy,2019
1003,Artificial Intelligence Based Training and Pla...,[{'first': 'Krishanu Deb | Pankaj Agrawal | Ha...,http://www.ijtsrd.com/computer-science/artific...,Training and placement cell in colleges is to ...,"[Artificial, Intelligence, Markup, Chatbot, La...",artificial intelligence,Bibsonomy,2018
1004,The Significance of Artificial Intelligence in...,"[{'first': 'Dr. Atul Kumar', 'last': 'Mishra'}]",https://www.ijtsrd.com/computer-science/artifi...,"In an increasingly digitalized world, the util...","[Learning,, Systems,, Artificialintelligence, ...",artificial intelligence,Bibsonomy,2023
...,...,...,...,...,...,...,...,...
4495,Phonologically Aware Neural Model for Named En...,"[{'authorId': '2528900', 'name': 'Akash Bharad...",https://www.semanticscholar.org/paper/f1a8ff55...,Named Entity Recognition is a well established...,NaN,NaN,Semantic Scholar,2016
4496,Large-Scale Distributed Language Modeling,"[{'authorId': '35797272', 'name': 'Ahmad Emami...",https://www.semanticscholar.org/paper/591080c3...,A novel distributed language model that has no...,NaN,NaN,Semantic Scholar,2007
4497,BERT for Joint Intent Classification and Slot ...,"[{'authorId': '47261124', 'name': 'Qian Chen'}...",https://www.semanticscholar.org/paper/476029ac...,Intent classification and slot filling are two...,NaN,NaN,Semantic Scholar,2019
4498,Language and Translation Model Adaptation usin...,"[{'authorId': '32278254', 'name': 'M. Snover'}...",https://www.semanticscholar.org/paper/b281a9d0...,"Traditionally, statistical machine translation...",NaN,NaN,Semantic Scholar,2008
4499,Commonsense Knowledge Mining from Pretrained M...,"[{'authorId': '2072080518', 'name': 'Joshua Fe...",https://www.semanticscholar.org/paper/f98e1359...,Inferring commonsense knowledge is a key chall...,NaN,NaN,Semantic Scholar,2019

In [19]:
df_merge.authors[0]

[{'authorId': '121645690', 'name': 'Sébastien Bubeck'},
 {'authorId': '143754359', 'name': 'Varun Chandrasekaran'},
 {'authorId': '2315830', 'name': 'Ronen Eldan'},
 {'authorId': '120962807', 'name': 'J. Gehrke'},
 {'authorId': '2064595436', 'name': 'Eric Horvitz'},
 {'authorId': '1783184', 'name': 'Ece Kamar'},
 {'authorId': '2212084492', 'name': 'Peter Lee'},
 {'authorId': '2109308930', 'name': 'Y. Lee'},
 {'authorId': '152244300', 'name': 'Yuan-Fang Li'},
 {'authorId': '23451726', 'name': 'Scott M. Lundberg'},
 {'authorId': '40900039', 'name': 'Harsha Nori'},
 {'authorId': '2542427', 'name': 'H. Palangi'},
 {'authorId': '78846919', 'name': 'Marco Tulio Ribeiro'},
 {'authorId': '144884116', 'name': 'Yi Zhang'}]

In [27]:
df_merge["authors"]

1000    [{'first': 'Matthew N. O. Sadiku | Sarhan M. M...
1001           [{'first': 'Seeta M.', 'last': 'Chauhan'}]
1002    [{'first': 'P. Naveen | S. Nikitha | P. Sudees...
1003    [{'first': 'Krishanu Deb | Pankaj Agrawal | Ha...
1004      [{'first': 'Dr. Atul Kumar', 'last': 'Mishra'}]
                              ...
4495    [{'authorId': '2528900', 'name': 'Akash Bharad...
4496    [{'authorId': '35797272', 'name': 'Ahmad Emami...
4497    [{'authorId': '47261124', 'name': 'Qian Chen'}...
4498    [{'authorId': '32278254', 'name': 'M. Snover'}...
4499    [{'authorId': '2072080518', 'name': 'Joshua Fe...
Name: authors, Length: 8279, dtype: object

In [32]:
def get_element(row):
    print(row)
    for name in row:
        if row["source"] == "Semantic Scholar":
            ergebnisse = [item[0]['name'] for item in daten]

In [33]:
get_element(df_merge.loc[0])

title       Sparks of Artificial General Intelligence: Ear...
authors     [{'authorId': '121645690', 'name': 'Sébastien ...
url         https://www.semanticscholar.org/paper/574beee7...
abstract    Artificial intelligence (AI) researchers have ...
tags                                                      NaN
query                                                     NaN
source                                       Semantic Scholar
year                                                     2023
Name: 0, dtype: object